var pt=(function(jsonp){ if (typeof pt==='function')pt(jsonp); return pt=jsonp })({
"2gmadwo7wlvp5ivib4wprqad":["pth","آتیش‌بیارِ معرکه"],
"2xdh3b4pqa6jx6drtplpemlk":["ptlauren","Lauren Rosen"],
"2zvmbc2xgl6pmrosaavccj3i":"pthibodeau",
"3lqn2ksgllb4fq33cwcquxka":["ptornroth","Peter Törnroth"],
"4fmpjbyk2pybax46u4dyo44w":"ptarmiganfan",
"5cz4542rwnmu6enppslil6qo":"ptswithpower",
"5lpba55we53l5h4egg2fsmhr":"ptc",
"5m75zhp7hc32ldu2ixqamiv7":["pts","Paul"],
"5u7xcqliflbsx4h3rqfzyrcw":["ptchronic","PTChronic"],
"5v4eacqx4ji3gt7t7hnnfky2":["ptrlrd.com","Peter Lord"],
"6jrk46j6jdnumfecn6yfs27n":["pthelo","pthelo"],
"7w2qc7ti2ig7mqdf4wcaqmoo":["ptisan.net","Ptisan 🦝"],
"ah62zlp7x3ki7rwwdabu2dnj":["ptitbobby","P'tit Bobby"],
"cgnfh7zmomgjxfxwhghk5fb4":"ptsdawn",
"ctrefctrsvmtjuuysbnnuikk":["ptarnation","ptarnation"],
"ehtsqpqc64ssac4la2wc4v62":["ptamitoboe","Jessi mit Obö "],
"enhltv7lljn4vmrh2xjihnyu":["ptr81","Peter"],
"gcc7ju5lrvn7vnoqxms3nqlq":["ptp","Farm and Hammer"],
"haerkc7iwklqdpluzdjyv5pv":"ptsine",
"jkdti5rdkft2lshawlab3yt2":["ptniswarcrmnl","Johannes 📯"],
"jnxet4uzxj7s7bcoprvd4qyr":"ptrourke",
"jqjlvj7lgebdufpl2qp2o3qz":["ptpower","patrick"],
"jqxpmirmi62np476idawiyet":["ptitsugus","Audrey"],
"jrdj5raop4yled2lzne77owe":["ptitjulien","P’tit Julien"],
"lohrljttlp7itidnxyzxd3wu":"ptaha",
"lpxxtajpbp2qaad3hord27od":["ptfilm","Peter Tedone"],
"lqxi3ynmxjdyoivrankedvvn":["ptd","Patrick (sometimes T.) Dorsey"],
"maseivbc3tqml3jrigscbumb":["ptibz.younghorses.com","Philip Tibitoski"],
"mcxkxnlgllqhhcvghs45pcwa":"ptoing",
"mhix6lnywsbeo7fwj56vh25r":"ptolomus",
"mkqjolhmqgexk2uikru25cfv":"ptb2003",
"mlfu6pxwxib7vtqrsgznxakh":["ptrq","Pat Walsh"],
"mwj7rasxawalixvjydmjkm7p":["ptipi","Ptipi (comms open)"],
"nmhkweujip3briluqja5hjqs":["ptrkbrn.com","Life Grips "],
"odecprilhlatg24pfbfz6exp":["pterosaur","Holly"],
"oexi4u3swttx2dopgekug3mv":["ptrckmcc","patrick mcCann"],
"owxqkhuastubsb5c73jltc6w":["ptrn177","ぉι゙ょ"],
"qhxzfmuphqnyaqsbq4xe2oli":["ptitenoli","Noli"],
"qvwoumb4wx5xqx7ldx4ki5c6":"ptiluc",
"r4np6ythjofgml6gog2tgxjp":["p-terg","₽᷀᷁᷇᷈€₸€₹₲̻͉̥͊̽📖🐦🐘🌌 🧑‍"],
"r6zq3ed5wlmbdtayv5dkmi33":["pterodactylus161","Kater Antifa"],
"rgyvi332ecycb4s3gfvwd4bt":"pterygota",
"rkeianzfdwfyztjep2huiyu3":["ptsantoamaro","PT Santo Amaro "],
"rlfbdayt2drwilnyxxrb2xpc":"ptexpat",
"s6us4m7kad3tz2tjhik6cy7n":"pterribledactyl",
"sgnbuxei7x6ycu4g33qauahn":"pterodactylus2",
"sgwm6svrzkpmfkohp52r4icu":"ptdnldsn",
"six47dus7fdnxv35ka75fizz":["ptklein","ptklein 📽️"],
"ssbx7dizcino5jxdnxtwfwm5":"ptclay",
"vd2eec2ozlfkq7yql2vifedu":["ptcklucas","Patrick L. 🐘"],
"vkgm4ujugds26ytgkgxbzjby":"ptfox",
"vynl6il44o4q7zjaudjtbiqn":"ptros",
"vzh3zejulmmtn7ckibpu5tjk":"ptrfrs",
"w6a5l7tch7kxabrlvi7rsunn":["ptttton","LepTon（幻想）"],
"wbmuie5xijt4agsapy5l6npp":["ptasia8","пані Птася🪶"],
"wl6chddxqumuzv3jnra5tqns":["ptaah.fr","Ptaah"],
"yd35y2xqf6clpy4uz4ia3hrm":["ptk","ぱつこ"],
"z6bifruijmguhzzm7a2wb5ai":"ptnobel",
"zgvmtcfcrbzghodvu7crj56k":"pteravictoria",
"zuvlnrzlrnavhqujzb2hz3la":["ptx","pourteaux"],
"oyi4zpnwxhz53habpndkilrj":["ptus","Hobbs🧑🏻‍💻"],
"dc4mcpgvbjmhlaj54encgcnt":["ptm","Patrick Marsceill"],
"zbokmq6zvdtabw252kztligp":["ptrbkr.com","Pete Baker"],
"gkvuftlwm23mvashdujnowcl":["ptl","Chonker"],
"7x6nljbnkpx5qhvt42fjw2dn":["pte","Paula Te"],
"67arm75hm65utqh7ucoci5un":["ptiza","Ptiza"],
"m3w5jvdoumbh6xspocsms2zd":["ptforsberg","Peter Forsberg"],
"jrtz3lgn2foj63qhutb3rj5r":["ptrujillano","Truji"],
"2em3rhcmfb3i535om7nkvv75":["ptsi","Philipp Tsipman"]
}) // 2023-10-21T16:08:06.293Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
