var qd=(function(jsonp){ if (typeof qd==='function')qd(jsonp); return qd=jsonp })({
"2c5oxf3jakzvmzq5vlttaala":["qdrunkman","Квантовый Ийон"],
"fejsz2e7wdd2hm5gd6gg6chj":["qdbp","すいちゃん❕"],
"fnsketwqpp25o2suaeuvbmkd":["q.drags.how","q (said spooky like boo)"],
"qmxpwahgwdbfhgga4i2i5qgo":["qdub","Quiet Warrior"],
"iv3zylcopq324n3xxeuqzqje":["qdot","The qDot router "],
"bwwk7wcfszvlec4r3goctsdm":["qdaz","Quarrel"],
"jbzlxe7g3tl5ll2eniq7evuh":"qdf",
"4dqdy67l5gkqvbda5wgwnifo":["qdepim","Quentin de Pimodan "],
"tysvjwtclc2anvjkuzy75me6":["qdc","QDC"],
"5vinhrv2mhjisay6xabtpdje":["q-dog","Quinny "],
"k7vz54kvcnik5ff7gm76zugo":["qdnubp","george"],
"ekzgh2ywz65gb3t66fpgfudl":["qdpoisson","lizzie is a wreck"],
"7rtaziz7rravxzwqgyizq5br":["qdavis","Queen Davis"],
"r5erjtaoyunrhc2vdjaregga":["qdazed","Coup ✨"],
"dscvu3tpcag5l2rbdpdvabfb":["qdork","jenny"],
"p33oysgxpkxz6wvzqkfqovm3":["qdn-media","QuoiDeNeuf | Media"],
"oyambgwdbedmtwqo5tfzrjfn":["qdr8","henry"],
"tjm2btjqkelyvio75nq7srhb":["qdcelestial","QDCelestial"],
"dzewdefvavxwsq73xbpxrzlr":["qdvbp","しき"],
"dmt5qzth5cxdgxrkrwo7ya6u":"qdr3",
"umw4vvgg7gyyabcfnh6vzb7a":"qdust0",
"qe4ljkjrdk2ckhka4epgh6wj":["qdony","Miquel Codony"],
"ysgqtasoyfhijmqie5xxlzyk":["qdd","핏져🍕"],
"o4kzipzbvyi4a24jew2cidp2":["qdnox","QdNox"]
}) // 2023-10-28T11:08:35.597Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
