var ct=(function(jsonp){ if (typeof ct==='function')ct(jsonp); return ct=jsonp })({
"24dtpurng7ey5qbst4plb5xx":["ctryuniverse-kjc","Country Universe KJC "],
"2atoetn2cnxz2piciythxueh":"ctrl-alt-defeat",
"2ux47pphhbvl2sitzqunw7hz":["ctpuzzlepieces","Donna ☕📚🌸"],
"3bk3puna54g5jgssmxii3o4w":"ctfsh",
"46dl7kbvhdkarl4vuojqitae":["ctrlphr34k","Ctrlphr34k"],
"4kcttgjpftdcfnsv4cnfbj6h":["ct0","ct_🌸"],
"4ngprmyzsklwdanlvhjlvrdh":["cteu13","Christophe Teuma"],
"5f5upoflpxmcwcmu3hs7q7mc":["ctcwired.paradoxwolf.info","Paradox Wolf"],
"5y3jpxouf32fw56ld6onuop5":["ctnash91","Charlie Nash"],
"6nyopcmfb7qjthhs4ix462bg":["ctsinclair","Christian Sinclair, MD"],
"76mxefozbork47rjimhum6r3":["ctrsteve","Steve Caimano"],
"7wbd4djwj2uqrxixvghju7rh":["ctintc","CT_In_TC"],
"bhsreifjineblpgi7hussyse":"ctardivel",
"bnspshapjlrgsx5w7usxyzvt":["cthuwu.fun","🎃Countess Cthuwu🎃"],
"c4u5fulvltu4znx5jxnnvrxf":["cthulhusdream","ᕧՇђยɭђยร๔۳єค๓"],
"c6xowpuoehf6ovuu2h2juu6h":["ctschroeder","Caroline (Carrie) T. Schroeder"],
"dplblqxbrmmnziklejyxt7qj":["ctstrph","CEO of Panic!"],
"emjwgtrglau326rvjjx7xew5":"ctrlaltd6",
"erbbtcw5pqhjgjrhxgaw6nma":"ctartisan",
"fu376e3niysrmsiechas4uvi":["cthomasesq","Charles Thomas"],
"g7zcc7mwgb7ny35xxz4f6kdf":["cthrynokly","Kate Oakley"],
"gmza6c6jn3ojerxzuosjvazz":"ctsamuraix",
"ivhla7zf4a3ucl27r2hbyywh":"ctnz70",
"jest3to722zplydpehbh7uwn":["ctpjano","Ctpjano"],
"jip6yjxrliocxmjxm7lkhcxu":["ctsalazar","C.T. Salazar"],
"k2ibqipb3qeehh7z42q256ub":["ctlnmsnd","Cătălin Sandu"],
"kwfk5qcqzrcv6jx7opg6va5k":["ctip","CT"],
"lupj7p6ogihqmwsd76xnemm6":["ctrlaltpeace","リッキー"],
"motkcy6lffjq4hbj64b52dkh":["ctconnors","Christopher 🏳️‍🌈🦭"],
"nptwdabjjt4uy2h3ctld7mtw":["ctfcrea","Corine Turrini Flury "],
"o5muswls5seadrzrx6gfyv5h":"ct-indigo",
"o6osbbm4vv5uxipveruvlyxq":["ctwpod","Circling the Wagons Podcast"],
"ob5uqwnrkkh6prvvuq33fc35":["ctrlshiftesc","Task Manager"],
"oca66uwzqjhs6tppzkeotjgh":["cthulhu23","Patrick Kelly"],
"pazpl4iiwd5v66gt273r3y2n":["cthulhu4prez","Cthulhu President"],
"pc7lw4yfxk6aidvkscdcmdkz":"ctg",
"plyulgd3khfkddgp7jxem35o":["ctessum","Chris Tessum "],
"pvxl5ytvx6u5vmexl6qgm5s7":["cthulhutentacles","Cthulhu Tentacles "],
"rrilxyqyjmsw2f456rcewhl5":["ctype","на чверть нудні коменти 💎"],
"rxcibd3qisrta23gzaqjwibx":["cthulhcc","cthulhcc "],
"secj4u3q7gxdlsi5oqkilivr":["ctsano","Criselândia "],
"tdoyw63vmlpfoomdtbadmiob":["ctrombley1","C Trombley"],
"tqxyroysdr3gc253u6j2k4vh":["ctrlalttim","Timothée Poisot"],
"tsjcrqnhvjfct7irwdxffbcm":["cthuwu","Cthuwu"],
"ttotgptj5jhsxkbs7m7ss32t":["ctrlaltglitch.fursona.club","Glitch"],
"uhuflxwcqrw3mwry3hv4e6tv":"cthugha",
"uqhsvttbcsiklrnqf4orxznu":"ctrlaltcassie",
"uwzre34cha62rth6nuuctvav":["cthulou","Lou (she/her)"],
"vvjwukbyx45mcvbsyhgfui3i":["ctheriault","Courtney Theriault "],
"vywtkh5sdcjgl6vwo3qt5e6q":"ctualtrex",
"wlpfqrdmf6jiekjd4rt5l4gu":["cthizio","thizio"],
"woqf5bakmtsnvbyy2mpq4zch":"ctaylorwrites",
"wzqfguyjc5zd7zmqnxe5glv6":["ctrlst4rk","Andre"],
"x5mtobtmwvkduggcimporjht":["ctrl4ltdel3te","McDreaBean [they/she]"],
"x6zmlxkuurngoed5dzbzjgiq":"ctplantdaddy",
"xxkclflna6b4jvtwtlxuz26o":["cth73","Christian"],
"xy6pydpxmlzte7gkf5xm5jfs":["ctownt2g","街坊撐華埠 ChinatownT2G 📍"],
"yi3fx23knwa7uaur54xf6vbp":["ctpax","CTPAX"],
"z4soqq22ebqgundmvfvs3hvv":"ctrentham",
"zdi6fqyicfhwj5cslvqi6uk7":["ctjhill","Catherine Hill"],
"urige7a5ztu65e4cwe7s7yrc":["ctogden","Chris Ogden"],
"3ebeobtqcfp6iivpwjzyrrgv":["cto-junior","TDM (e/λ)"],
"6zvkbzg27on2wogpam3p524v":"ctforester",
"weteap2swqbijpgta5vg5dug":["cthulhu","Cthulhu "],
"kbs7d52jxhteajiw4sds7yjm":"ctd",
"rxiqfocyqapd55mvxc46maol":["cto","Curious Cat"],
"vrn5cplxjidvw64tzjkwsety":["ctf","César de Tassis Filho"],
"qayabd2ihoocywiuhs7rmgsx":"ctschad",
"srozua6cuce7ccdiramyv273":["ctomeo","Chris Tomeo"],
"2jxazas4k4cs4av42gggbzya":["cthrin","Catherine Shyu Sullivan"],
"mslrmcg5y3foqa42rebbuunv":["ctide.com","ctide"],
"ig3amyhok7ipqlje54gwlvoo":"ctan",
"4z63b4ztgi33nynyg4jt2cnh":["ctlfsh","nisha"],
"vxq5brvqkae3lgirt6paemzj":["ctfreakshow","Ian."],
"2rmoms665nkww7dl26dw65hs":["cta","ゴットン"],
"732z6s2zgfhnb7xe3e6el2lr":"ctnzr",
"yoz3wkibzpjwdf4fclwmi2dy":["ctpost","Chrysanthe Tenentes "],
"5pjc7s7ulv7tz76u3xdxcpvo":"ctalbot",
"fmxmdkxhj6dcv2pmvq7edvbc":["cthulhu630","Cthulhu630"],
"olevhrdacdz6sug3ycn3wvtz":"ctbeaver",
"pcejcn7dvnxpklwx7xbxnqup":["cthelala","Chirag Lala"],
"sge5xzbznrih6f6njfaahewj":["ctoothaches","cocaine for toothaches"],
"lum3tsvs5atca4hyswg4qnly":["ctl","Connor Leech"],
"sncyil5g6dvbrldlvhqmb2xq":["ctrl.red","audibleblink"],
"j4twy4u5i77ycxxk7florcqt":["ctbarna","Chris Barna"],
"o3cu3w5uyaawh3aecmgthkon":["cthulhu.network","Cthulhu Answers "],
"6hgz4nnxxmk4dd6oikzcq2sl":["ctafails","CTA Fails"],
"vumprdu4pbkt5mbj3fv2pzek":["ctyar","CT"],
"ylrj3vcqzpjczqgh3pi3mqx4":["ctrl","dante"],
"treelpumtogswskn767mdswv":["cttwentymusic","CT Twenty"],
"xqhh3ddtvlkwsotjbfqerhrb":["ctdawe","Chris Dawe"],
"g7dubvdgsunwqgbmixgcijzp":["ctnjtp","cxtxxn"],
"yamdn7kaupskd4x65y5lgi2p":["cthuluboi","eMBee tHe iGnoMiniOus"],
"tvuxfxp2nlycpu5s5hjuxbkm":"ctrlzac",
"bquppfwfk7hgt6f6rd3qr3cy":"ctakao",
"gbkqlwslfvyhxrg7vkqpt6ns":["ctisbilkent","CTIS - Bilkent Univ."],
"j46tfruacf4hlpbc3lzllwr2":["ctrlsaltesc","Salt"],
"nq6uuszw3jrg5kuz5jznp3qb":["ctn","Christian"],
"jwozxhsfjywwm3qxwjuve35q":["ctrlaltdefy.com","⛊ DEFY"],
"layhzzn2qd3lftjl2so4bybk":["ctjones","ct jones"],
"uijxd63lnatobtjmevdhcf2l":["ctr","CaiobaPiranã"],
"lbvsicq5z2ria7ofjwi7rxlf":["ctrader","Cna"],
"eecrpd6c7xysur3oxtjitcsr":["ctugba","Tugba Cevizci"],
"l7b7cpdj2fvh5gqa6g5cr7cg":["ctln","かてりん/katerin"],
"rmohrzywmmka2zca26wulp3r":["ctchen","Tom Chen"],
"nav42327x6qectxdiejschit":["cthrushell","🕯️ c.thru.shell 🕯️"],
"g4qtggrbv6hwguyesa7crszt":"ctx",
"qjahezk7kwgx5h7mvjytmpug":["ctexposers","Capitol Terrorists Exposers"],
"qpjjupknfup5ooxidm6rf3cl":"ctothed",
"bm62daotheoent7xe3m7pgbf":["ctwhitacre","Curtis W."],
"j7j3iedbc6zvvx667hy7xduy":"ctjinslc",
"un3c7ed665cfdfob3wlm7r7o":["ct6502","Chris CT6502"],
"6shh4fk2bkvuvw6dpuymqydo":["ctzn","CITIZEN"],
"olwiytzfurextbo65qyb5bxz":["ctanimation.com","Tanimayto"],
"slggzqmbn6nznfpowa2rvdkp":["ctrix","Massimo C."],
"fqz7ho5hlksdxbb4tpmqbuti":["ctnhkn","Hako"],
"tgquzrfywrgezycesi3a77fz":"cthomson",
"l2tjshjet54oqfycwxdxjvge":["ctotheatherine","cath ☆ﾐ"],
"p64asyewadpmz2dvdic52hz5":"ctrlspice",
"i35ibhthwn3qujddzcdlkdwg":["ctaylsaurus","christie taylor"],
"twszacwqckuwii2hbwqi6t6f":"ctc",
"6are75clwsf3wk3o3x7tvggz":["ctlin","CT Lin MD"],
"sunw4744tpjwye44tukprjn4":["ctecmiis","CTEC"],
"scbgp2r4ipz27zetnf2cxdjj":"ctavery",
"sldutwg5dd3robtr5i2ba5u5":["ctrlaltfu","CtrlAltFu"],
"kcixiuymocclqcm57k24pdql":"ctlphoto",
"2wnfjnef4tst3wsaentgx2v3":"ctrombley",
"5fitg2loedjidaeevirs5uxh":["ctrliphones","Ctrl"],
"saxq2os2ia5lhfg6tg3iv6zm":"ctk",
"jed6xvrwqapcf5f7u2cfzgqz":["ctborder","Baseball Turntable"],
"jsj3mw7z34xr4i56duaqmgx4":"ctrlalfsdel",
"jx5uy72236vebpluvazkeidy":["ctrclub","ctrclub"],
"6i2h5mkjnqthzepusqv5vhmv":"cthomsonr",
"6ql5ytypitfamvnf6jfc7elk":["ctdem","CT Dem"],
"26gn2t7zodxhghv7psyu7n4m":["ctoner","Casey Toner "],
"a6d6h54r3pjpfw34t5wgv5ov":["cthulhuwu","lockheed martin pride float"],
"wp5q6u2422a4cqtfmipebnla":["cthomas","Chris Thomas"],
"72eglohgm2nt7j4suxylkaka":["cthunman","Carl Thunman"],
"lf6l3si6nf4ulmxcfwpkdfoc":["ctrent","C Trent Rosecrans"],
"dim5cjhkunbwyyfialyjrcqg":["ctdessi","ctdessi"],
"jovduosnvgoq7huydcafpli4":["cthulia","julia 🪼"],
"3ujr6xsan6ye7hd23utofqsl":"ctp",
"q5u4knufbor2hhpgxv3ku532":["ctrlz","Undo immediately"],
"2osfuxgmhbk7nq7fukdmgeya":["ctcoach","Chris Tran - The Most Player Focused Coach in the World"],
"74i5qo3n6tzluyicyd3kfvxe":["ctamyildirim","Cihan Tamyıldırım"],
"zn3gdjro3fk5xvltnwngu3tt":["ctserc","SERC - The State Education Resource Center of CT"],
"he2lkvdpuq3vnsnludc2r5im":["cthomasjamh","Charlie Thomas"],
"wp7ult3gvitfwjaplkkmfmiw":["ctxt","Jeremy Long"],
"cmga2jypmy7a4zuxemcb54yw":"ctslick",
"ol2jzurow55wcehtrcffwdt3":["ctrlctrl","fleshman"],
"yndrb7ug56ehxevgy5eezab6":"ctphs",
"io7b563jcmkne22xczd3ydgd":["ctford","Chris Ford"],
"zqzwuxkqafcnw2qx5gw2zopv":["cthomastech","Chris Thomas"],
"owpspo6ddcvpvfyhcv4f5gty":["ctedd","The CTED"],
"tbjtm24ibnv4me7tqokzytdm":"ctreatma",
"xznydzedcno6tu3lfv2urdft":["ctrlaltdelete","Deanna"],
"mfy7tvxcbjhbuckasvpinlv2":"ctw195",
"2d3cuie7xdaguj3gfyjdbnln":"ctyrider",
"ue22dceklgzwjhpdkqzqj6cs":["ctupramod","Pramod Indunith"],
"d6g2tts66ytqfslwhna3dk7b":["cthulhuyyc","Cthulhuyyc"],
"crgulloe4j4j5qgnnywrw5kr":["cthonical","Cthonical"],
"rfqc7cl5pt4dsblulnbnfaui":["cttboy","Mickey."],
"ssta4pti6osevyvktnfwwv7x":"ctrleo",
"poeqyckhy2lr4mgupd3xer3l":["ctill","Christy Till "],
"vuoizhhvkt6sennwrdjommam":["ct-atlantis","Nate"],
"ysdvquj2jrfiinloscgb4by5":["ctrlrafa","rafael"],
"laqbm7zo72c54pbpk6vs5eql":["ctklimansilver","chloe"]
}) // 2023-10-22T11:44:51.646Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
