var jf=(function(jsonp){ if (typeof jf==='function')jf(jsonp); return jf=jsonp })({
"2fg6nqvpmpqe3qqjfe3ohhjh":["jfruh","Josh Fruhlinger"],
"2ptqgg335yb5negavlhu6g6s":["jfmclaughlin92","Jess McLaughlin, PhD (they/them)"],
"32tiutqgp7yswtrstdzohhab":"jfotis2dabord",
"3ricjjbkac4mh4l7vf5fejga":["jfsculpts","Jesse Farrell"],
"44fczkkycq6k7u6xnubsgmvm":["jfd","JF Decoster "],
"4jl2ilkahsqtyywlk3vdpxuc":["jfb1066","Jonathan Boff"],
"4vkfkwuikltlmyzrym7mdmyb":"jfdt",
"5dxcmzb7aesvp3wk524c7utx":"jf27",
"5iemlf5iin7muhdyvr7fnsha":["jfwinters","Jane Winters"],
"7a7shqufy5rjdu3xw3d3khsa":"jfoleyjr",
"7akafu3jrrsp52ew7dss3u7i":["jfkenney","James Kenney"],
"a2x5z3piche7ietsgfawzwgs":["jfry","fry"],
"a4wkah6zl2rptmyh6go3yi6g":["jfiliatrault","Jason Filiatrault"],
"bgdd32jwqetqvndidnnn2qew":["jfarrers","J Farrers"],
"bsuojtemwia5acaok3feldfd":"jfroholt",
"ch67finjvbh2hj4qi6hgs5kc":["jfversluis.dev","Gerald Versluis"],
"ckbcldejfy7mnsthto4ypcgv":["jfjun","jun"],
"cs74dbf64pu7vqisxy3puzhz":["jfwellspdx","Jason Wells"],
"csctkyzekxzir72ab4pcle3s":["jftitone","Jeanine Finn"],
"dhcczq7kmjv6rejg6a7pnbiw":"jfeyrer",
"eet3vczcqhphxnto2pnoqq54":["jfearon","Jim Fearon"],
"egxlj7omsmlnrtedkxqrpdii":"jfrickuga",
"fmhua5ud6ucf5gdyc7qvkjle":["jfrcoates","Jay F.R. Coates"],
"grxyildx5haph2lwce5cteyi":["jfx316","*Account Reactivated*"],
"hizyrioijdsnwa55zqkkblwu":["jfkav","John Kavanagh"],
"iuyvpamrk3mbbc7zkdw5iezw":["jfam","Joseph "],
"izbsqi4ki65i664p6vro6osd":"jflu",
"jxvs4azlwo4gu2xtigog6pvv":"jfgreffier",
"kkvxfvr2yjqpjk4csrmcbpgh":"jfnilsen",
"kysi5ggy435tt6gcdht655jd":["jfriday.com","Jess Friday"],
"lg2toihiijhrxhxprjazdzoa":["jfuzzy","Jenn Marshall"],
"mny4xywxqowruu3xh6jwqbrg":"jfennellauthor",
"ndmdn6dngju56h5j5vb6uxyn":"jfs",
"notxayxtdwkyg53xnm4gd7vk":["jfive","Jonathananon"],
"ntbelae2e6ksg6eambvippw2":["jfeej","Jeff Fijol"],
"oajo5gsvrxmqebpcii6cjbvw":["jfdubeau","JFDubeau"],
"pjuohagdlfoskywys3fm5heo":["jfhil","John"],
"pkjnh6ck64apuvesix44gnkz":["jfaniandytp","JF - All Toasters Toast Toast"],
"ppu6aw34hwoovn3oaq3l4ose":"jfweehawken",
"ptsunip4betts3dtqnqfe3oq":["jfox","JFox"],
"r5eoeosdtq6bkzry4lvh7lr2":["jfalcon","J. Falcon"],
"r7i2ylbjkvhrzoimizlwyen3":["jfx9","Jan🧘‍♀️"],
"rae6skqe4a3nazpx4zqv2xta":["jfcdoomblade","Reyna Cervantes"],
"ri5b3hjo5foqsqe5cdpu2qcn":["jfisher","Jeffrey Fisher"],
"rstmdnlpmwmvuc4tbfbegmc7":"jfritte",
"rv6yuvia6ekhwiboq7uyst2k":["jfowle","Dead Inside"],
"rydbs7szpl345zaatfgy5pfb":"jfswift",
"scgohqpw5lwm5akyd2m7l3p3":["jfleck","John Fleck"],
"svuctwhkntvaa6bdtzjohyvy":["j-furfurylthiol","J / I'm an accountant"],
"tclnapqzfli5aosdwfmnmxei":"jflhere",
"ufhy54ojnrhk5gtg2v4cvu3j":["jfchose","Jean-Francois Chose"],
"uiqvqhpickhegmonscaiytp7":["jfin","Jake"],
"un3dc4uksjuknwefmixqhhd2":["jflb21","Jessica Borges "],
"vnb4vohmhlbs3twdzoq4bvc5":"jfbrews",
"vomw7ifrmg6nwty6oxewqv2f":["jfac","Jack"],
"vv2qzprztiadwn5ch5ot6fgy":["jfallert","Joachim Fallert "],
"wbzgo5dm4jzchhyl7bzbh6zn":["jfporchez","Jean François Porchez"],
"wkkydsmmry3ccungrt4xahcs":["jfavre99","Jacob"],
"xkqvzftu7mwnx4vusxrq5yfk":"jfelixcardoso",
"xmb25pe3d2eu4iqeomnz76ic":["jflagg24","Arbiter of Comedy"],
"xq6qcsyai7ptqctc66mna6re":["jfoley","James Foley"],
"xuwd4glve4pbj75hwzsmsepo":["jfclifford","JFClifford"],
"ye6btccre2dk5tjhhmhso4xn":["jfudge","James Fudge"],
"yhwb4flopeavzkwbybtojo2s":["jfallows","James Fallows"],
"yqojrk46rg4nbeu73ejpwhwa":["jfors","jfors"],
"zflcrtqmb7pcwouiixuf22pq":["jfg","jason grinblat"],
"zhqcxwgaf64x3utbv3sn4kmm":["jfitch","Jason Fitch"],
"zjc6coyf2wifffep6frotq6c":["jfbeacom","Jenna Beacom"],
"zlnd7i2zaaxe2624h4ci7is2":["jfriestv","JFriesTV"],
"zt75zgidf47upr3lltf7fybm":["jfbastien.com","JF Bastien"],
"wbqpvgo32v3g7agr3wykeb3v":["jf","JF"],
"egw3oz6hctior72xb6xfrkfs":["jfiadeiro","Joao Fiadeiro"],
"hlwfhfa4rtiyisld7tcjx7ck":["jfslicer","James Fields"],
"yrkucmqujfrynzaig7dunnv6":"jfblucas",
"ty7e7ebn27rrplva7jitlgd5":["jfornear","Jesse Fornear"],
"7k372w4goykra42aa3wcmm2p":["jfryman","James Fryman"],
"6wlrfyljh25ymq5dp65tihm2":["jfrejnyc","Jews For Racial & Economic Justice"],
"7xquoqkwbmnuga7lccq7noms":["jfoust","Jeff Foust"],
"3ztudmwchwxtv27kjyaqudmh":["jfrancis","Jay the Analyst"],
"bgqs76igbsqrsmsaanx4sbvs":["jfzappone","Frederick Zappone"],
"q5w6r735cxay4h2u7malgse5":["jfsiii","John Schulz"],
"oxtqpbmghrndwtrrovm6j25j":"jfb",
"4a23fukmmdrluc2ob7rb746q":["jforman","Joshua Forman"],
"bpnjnlgz6nv67elt7cqsje5u":["jfm","Jean Moncrieff"],
"7wisjhiwjxt4qy4eqfp27txw":["jferguson.info","John Ferguson"],
"l4ptm4hv36chysutalyf3s5g":["jfairbairn","James Fairbairn"],
"43y2e6avhf5g2gohg3scs74y":"jfrick",
"g36spzky5rcdfm47t2i3co2r":["jff","Jefferson"],
"cadaqpt2psqobppxlft2mktu":"jfrey2223"
}) // 2023-10-21T21:18:48.039Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
