var jm=(function(jsonp){ if (typeof jm==='function')jm(jsonp); return jm=jsonp })({
"2bhd3kqjpmv6zdt2qeggyakn":["jmquinn","Jonathan Quinn"],
"2eodmqum37g5utbi6ykgoi3s":["jmzyam","jmz"],
"2epknt43qulf63tuaun3mvxh":"jmaphis",
"2v2fa4i42pyc75i6trtdtshu":["jmzed","JMZ"],
"32t44vnp2gdd3cm7fmi565ux":["jmmendez89","JM Mendez - 1UP Vault Manager 👾"],
"33l4vwv2ylgdvqhlyb5xzzre":["jmawork","jay marie ⛅"],
"3dokguunpvhfnmduxnfknh27":"jmendesdemorais",
"3njnqmrzuv27qe4iepspfuwg":"jmittman",
"3tjcehtjqbfgznh2ajo22bom":["jmes","🎶"],
"3xuf2djn3vxt5vpx4v7t4o2g":["jmvtol","Jean-Marc van Tol"],
"4hc77f3czkmxklrgsfelzb3z":["jmuk","Jun Mukai"],
"4i5r2mqzbnbzavna53wmp25v":["jmarsh","James Marsh"],
"4jjhnw76a3mg2vulwv3kzric":["jmproust","Jean-Marc Proust"],
"4kgbviwcgxudbwug3wb7docf":["jmolawre","Janet Lawrence "],
"4lamyktixuch5syirj7ladgk":["jmaylax","Nina Bonina Brown and Serve (he/him)"],
"4lz3plwcwnxatf343t7lrqjs":["jmings","Josh Mings"],
"4nfeqas4rkip5vlx7qqtxsbv":"jm-music",
"57ghvki345qz5pua7ivos25q":"jmeyran",
"5ft4dj7xjakd33tc22hld6ho":["jmigozzi","Julien Migozzi"],
"5l4mk5zauaie6owwr766gghc":["jmrz","Jamie"],
"5lpyoenmzynuz3cfyjcguvje":["jmason1222","J.Mason"],
"5o5qjjvjtkyqahkus2ssraqv":["jms78","James"],
"65p6mwjylbr6fihj4g5xun3b":["jmgabriel","j. m. gabriel "],
"666lchspvosgadoh63vlvgcb":["jmedeiros71","Jmedeiros71"],
"6fss2scwymzumw3s27c4rjkz":["jmpensylvani","Maktoub"],
"6h65j3hj7vcvpekz22dl7hg7":"jmaxmuller",
"6i6mdktey63h2ssnb3mg6luh":["jmhodges","Jeff Hodges"],
"6iofrfaiu4hu7hy5c4mxpb27":["jmteakell","Jade Teakell"],
"6kajjk2l4bhrc54dnpns7lnu":["jmhuie","Jonathan Huie"],
"6qxkcatoyj5ybrnaght2ylim":["jmicheleing","Jodi Michele"],
"6vfcmqrbqcgbmugapjt5do2h":["jmkreiner","Julia Kreiner"],
"6whfsx2wikms6en6gyyuv4hv":"jmoneylai4",
"6xdtfbz4uihz4jzmiirdpbb6":["jmcsweeney","john mcsweeney"],
"6yv2us3hzys4fqcpn57nkqgr":["jmotist","Jmö"],
"72fiogdcyxtnq6uhlxkjgvt6":"jmarquiso",
"7ddftkomtzz7a3jqlrxwmtbj":["jmritchey","J.M. Ritchey "],
"7elpvxseqhasf7k326pvdgz2":["jmhart","J.M. Hart (rowjimmy)"],
"7o3747rpz5yz5ixxmr3gahmb":"jmgoatse",
"7s66wuaeztpzmbqrjf2735h4":"jmcminn",
"7vubmfaln3py5n2pmwms7z34":["jmarshallnz","Jonathan Marshall"],
"a5uhilxwplomrvw5vr24nl5s":["jmathias","James Mathias"],
"a7rmdmj7evedbw4momameosw":["jmluna","Johanna"],
"agv3ndeq7cpzaqqgxoccds3c":["jmacfuss","Jennifer McLaughlin"],
"ajf2wcijdkpxsb4txtzqefrt":["jmarcus","Justin Marcus"],
"ajv6xdjmqawllybc4tvjsu6f":"jmh53",
"ajy55qwz4hukiqx5npevvjwr":["jmbeveridge","Joanna Beveridge"],
"allwmz7c77x7hszhbxt4jivd":"jmj94",
"av5v6hp4rw4obw2e7bzzo35c":["jmulkerin","John Mulkerin"],
"axer7jaso6yzmfpd27x52owb":["jmucchielli","Julien Mucchielli"],
"b4mpit3kjinf75igwvkajepx":["jmenka","jmenka (commissions open)"],
"banhhkbc3x63expsympba7qo":["jmarkedx","Pup Axel📍Bay Area (Folsom)"],
"blssn7r22tpxe43u6635x5qb":"jmo2",
"bnyr53zc4iynay7kxjd5gpar":["jmanumeza","El Manu"],
"bqkrzxfuas5jc3p4tg7uduah":["jmsv","James Vickery"],
"bxhsypvxqyxkidbj32lycwg2":["jmcbroom","jimmy mcbroom"],
"c743recpcnshp7nyhu6s6ejl":["jmeiii","John "],
"cbyxtypvgzi65ong3yf7t735":["jmarieray","justine raymond"],
"chseaec3ssdua35hfmfrbupl":["jmgannon","Joe Gannon"],
"cphlzps36onqcc7k7wnnlxqc":"jmijarra",
"cw25zgx2mkdbc2r2wtzlhyap":["jmarshallfreeman","J. Marshall Freeman"],
"cyke4fd4we7hr5yndotlwsr7":["jmank","Jay/Jess"],
"d3ivivnkdfrb5uhddkp6plmd":["jmnphillips","Jim Phillips"],
"ddrmlycrsg5ko5vh2v3h2ubp":["jmechy","Joey Mechling"],
"dk6mvtszxowrqvnlxetqpmy6":["jmarthaler","Jon Marthaler"],
"dvjbqrwhajwpta4eczygmchc":["jmloras","야기"],
"e2mrmr2kztibaai4yjzktdm5":["jmungiello","John Mungiello "],
"eesn3xv3bllh4h6syiu2w477":"jmteo",
"efkh6abis22aewxcqalmi5vl":["jmattmke","JMatt of HashtagMKE"],
"en5hr4mxbxy6xefcmjucn3bi":["jmichaeldonohue","J. Michael Donohue"],
"esl76ti2skdxjvhu52auc5lx":"jmembalestek",
"f77ileh5dl7dhpkginjbigqc":["j-m","J."],
"fm6wl3kjxigf5h5esy3g4akn":["jmsbooksllc","JMS Books LLC"],
"fmfodlrhzrq442wu2mrkmlnb":"jmillwrites",
"fmjxlxkp7ndnadbe7wyg5svf":"jmcgarry",
"fp2gnanyyiqgusoiej4i45qx":"jmaerz",
"hf7n36ehgymxzowp6z4izcwn":["jmseaborn","JM Seaborn"],
"hgl7pzhx2w56ouuflccyvpeu":["jmrivera","Joshua Rivera"],
"hlnzfzmzr6iqqhcfpglo73jd":["jmijin","J. Mijin Cha"],
"hvhnelk5o225l3sasbbsia2d":["jmatlin","Julie Matlin"],
"hydqst5677gzh76agkx5wqvq":["jmilloy","unpopular historian"],
"hys5vnffpe3lxog4wpizlnqe":["jmariye","Jenni Lada"],
"i2zrs4i77oamwjrvjtmxf5uf":["jmcelroy","Justin McElroy"],
"icnk3s24kt5ghk6ljbgwauw2":"jmbeastmodeon",
"ih4qsavxkbwgjeglbrdjocgg":["jmh.xyz","Jocelyn 🏳️‍🌈🦄 🏳️‍🌈 "],
"ihkpy2uxtojl2w3vhkpfvbwd":"jm1ce",
"ihto5ws7at4cadccub2nyl54":["jmdlive","J. Michael Dennis"],
"ikukn4i2wilptlgoubm6oujk":["jmkeep","Michelle Keep"],
"iqcyyouhs2i5bslbnpl2zymv":"jmfaulkner",
"ireufrerhfja3jk7fhb6ftre":["jmsdirt","jim"],
"isrw7axhcipsmygabqyjfrlg":["jmkliegman","Julie Kliegman"],
"iw4zik7u5zligtxo5zkry7ie":["jmerilainen","Jaakko Meriläinen"],
"iy2pltzzepiwyrtjh64pzvyw":["jmz","Jeffrey Zuckerman"],
"iyog2tjkap6bttkuzbvjmpet":"jmrgby",
"j6csav5ztae6dj3c7pzr2awu":["jmsl","Mark to Markov Chain"],
"jh2cvhrntjeb4uw5qhbt5k3u":"jmay10",
"jifhxi76jzlj2b3mlkxsdqvn":["jmargotcritch","J. Margot Critch (Juanita) 🌴🦩🍹"],
"jircbga2uckxks55k6rnfwau":["jmill","Jmill"],
"jkpt6i5naboodg34unhjp4jq":["jmdubc","Jonathan McCarty"],
"jvzuxw73z2vlgtukurg6yhgr":["jmjc","John Canavan"],
"kbb2kap3pwgbehin6ouxha62":["jmthecrow","Jmthecrow"],
"khh3g3px2m54qzjyqolxqgx5":["jmhenner","Jon Henner"],
"kkuulldzzfffxnhss4lmksck":"jmgrygiel",
"kq64n3qr74g6zjjgkvmpy5qr":["jmcolmer","Jonathan Colmer "],
"l6slv6vv7xmquktvrwxnbab3":["jmiaminow","James "],
"lspq7pa4t7k2yycbpliqlj73":"jmatonak",
"lt3anay5wdtr4s7sylyxie56":["jmcristan","jmcristan"],
"lwyj6wji6wtwx3krr4q47rcp":["jmgreene28","Cloud's Strife"],
"lyyuetll7iykd5paqviag5zh":"jmaynard",
"m6ua2ujxp7r3ytsnp33dzjeq":["jmakula87","James Makula"],
"meo4vnpaxxljeaei27r2ne4e":["jmlafon","Jean-Marc Lafon"],
"mknh3sri3ozohzx7vel6pbhv":"jm6k",
"moyy5pju5i75p4zavjs525lp":["jmtrevisan","JMTrevisan"],
"msks4dhw2vvkzkbrq2cnnbwc":["jmoffattwrites","Jay ☕📚"],
"ncxkuvkdhskvhblrymm5yck5":["jmmc","Julia Coursey"],
"o3zohwecjkgwjpjnhwggcn72":"jmorris14",
"osnx5kgyzc4knihxmv5r73mq":"jmmfernandes",
"owxoa5osbrnhrg4qayemko4u":"jmlecornu",
"ox7quaokwu62gkjbbzfqidv4":["jmcn","James McNeill"],
"pdrofzwpsx5bfnktochoidsp":"jmessee",
"po2vwh4ejv7ha727rd4pmoas":["jmlc11","Jochy"],
"pv77zvzvsm5c3j45jhir2ebx":["jmricotta","Joe Ricotta"],
"pw2uuuv56avsc4vkbysthtus":"jmelville",
"qgczldbc54cgkmkcmqwidbl2":["jmorais","José Morais"],
"qhwvhai54ruidpllmklssvlt":["jmichaelmull","J. Michael Mull"],
"qilqody6wpz35kluxonqws53":"jmtamere",
"qs3ycbys55leerorvh2ui5ro":["jmarotta","J Marotta"],
"qx6iqruyaybrtw6cjbzksqcl":["jmcolberg","Jörg Colberg"],
"r4vcm5xmvwct7aj34b4hg4tm":["jmanna","Manna"],
"rcj36q5se23hja36kubiozkr":["jmittell","Jason Mittell"],
"rl2tcbfsrcmdhjflxgudo6a2":["jmut84","jmut84 🌻 "],
"rodclliqc47jcv4mi7voe5me":["jmarc.us","Jeremy Marcus"],
"rsepegcpnxw3p4j6jbeis2bk":"jmpira",
"s2ndwlljhz5e4h4d3xjgreuo":"jmanes.me",
"sc4lluoyzn2kbz4ue2be5ubh":"jmadelman",
"shuidoudznsg3rlbg2uiuinn":"jmq",
"sk2eg2omeqog2cnkoptbzxfw":["jmelikidse","Jonathan Melikidse"],
"suq3k37x4ejaq4b2j2g2v3cb":["j-mike","J-Mike"],
"t3cxlw4ljhrzgmlobiwly727":["jmgarber","Jeremy Garber"],
"ti7uays2jhcx4yz3w7meoh6t":["jmchatwin","Jonathan Chatwin"],
"tuxydk3a7btvxhjv7lzyjxjc":"jmaclean",
"txpw23yc5t6cdoysjsdu2zea":["jmccance.dirigibly.ltd","Joel McCance"],
"u352xe3cdmqtubaa5j3u2ixt":["jmcools","Jojo M. Cools"],
"u5xixvr2ouzl6tmghzhnn265":["jmacorreia","João Amaro Correia"],
"u7retysckxehmbbtaszuwm6b":["jmrosedale","🌿 Julia M. Rosedale 🌿"],
"ubqigrgwiegwjnltuzs5z2ng":"jmoodz",
"uiwha4m774mwnusjj3uutqql":["jmcnutty","Jeff"],
"v2lx6ewsnvv2pgbaa5rbcek2":"jmwooldridge",
"v2ozhnd3ar5mnuvchwvmpf6l":"jmellish",
"vea5zdac5kuxdsm4gezjynzi":"jmavants",
"vfpospjhepvpe2s5kvpm524o":["jmfinn","Mike Finn"],
"vlo3zxogayv3fr7i6yzfjufq":["jmiers230","Jess Miers 🦝"],
"vn7jqxzzaq5lszk2tyaoz7rb":["jmorton78","Jeff Morton"],
"vyhktggnnyu2muobi3dxhvbl":"jmdklp",
"vz5kt5vqqhs45ki3t5p4ilhw":["jmauricetitus","Jason Titus"],
"w4bkt6m2lgwhx2jkr4xegrtm":["jmac22","Jeff McGill (Participation Trophy)"],
"w4usjtj3jukkmqasqxczepux":["jmrsalmeida","🌈James Almeida "],
"wag7fvz3qcgshtqh2fonv4t7":["jmood88","So Sayeth Black Lord:"],
"wdmsbnnocannab7za5knekkj":["jmes.tech","James"],
"wkgszwb2v7kidss7brkbrrpv":["jmeno","J. M. Eno"],
"wm3emv5de6fi3hlmazw4bmzj":["jmelul","Jer"],
"wpvdcz26di2ahwayadkvmwhi":["jmorgynwhite","J. Morgyn White"],
"wxifopdsnbymkxy2fqpvg3lx":"jmarsh4037",
"xgacnvtaswkd5fgk4eiiwvcb":"jmnewman",
"xms6imovt7srw66xclpasnov":["jmfenner","JMFenner"],
"y7kzytfudwxzyoirjk3p7m4f":["jmertens","Joe Mertens"],
"ybk4pudzyyozddrymzme3mza":"jmr8675309",
"yobfmbmsdfdevr3cfxym2hol":["jmdau","James Mac"],
"ztmij2oui6vpnm3xscm7garz":["jmcsms","jmcsms "],
"zui23vvod6hylmly6d5yfdgg":["jmdematteis","J.M. DeMatteis"],
"zvlab2iyyhdhjmnryuuqoeq5":["jmbcafe","John Michael"],
"zx3zrabz7gzrlkki5r3wzers":["jmglov","Josh Glover"],
"zycvpozxhzfepkucjytsj7jl":["jmille99","Josh Miller"],
"37yhachn7lztvzs7dkb4kjml":["jmosawy.com","Jeff Mosawy"],
"zw3ocdw4r6qjavtjt6b3rn6t":["jmikesmith","J  Mike Smith"],
"2lc4y7rwbtdvdlgfqqmpu4j6":"jmg",
"zjncq6hdz74ktliaiiuzosaj":"jmymy",
"pzzn6zfi5brz7ed4alaudbfi":"jmidd",
"7wj6nj4v5dan3yfjkyij5egh":["jmiller","Jonny Miller"],
"uydng422bruomgvybhgsyquk":"jmb",
"2rmj2g72ynpsv2f525gzjsiq":["jmsturgill","jmsturgill (UmpaMTG)"],
"cxdblau53inuqyblf4gsqbg3":"jmbmd",
"t6wkblladhnsgxrmlq4auakj":"jmore",
"tbmg2odp3r5f4keqhtx3khgl":["jmcavalheiro","JMCavalheiro"],
"4t6np5qd6lbhnzu7vnrgql64":"jmillr",
"yxx4e6m4x6vc64mzkitvadqb":["jmtg.net","Masaaki Komori 🫥"],
"3q56kkpr3jnyil4qsokgj5ld":["jmdacruz","Marcelo da Cruz"],
"5ikggxvn66gtiayjpw3dn6rs":["jmc","joseph cohen"],
"dgyci5cstkkeqqv7potkhe75":["jmm","Jesse McLean"],
"efk6gpv5qjk5ai25723hnf7c":"jmurphy",
"qo2p4d72mvwn3qagxs5av6oz":["jmo","jmo"],
"xauwigjv4pgxccrut757j4yd":["jmct","JMCT"],
"uftkg5wizkex2ibulfslbp74":["jmcmichael","jmcmichael"],
"uc6ufi7lcfsmar3p7j2gyh6g":["jmart","jamie"],
"7c6xsedjcwocqfu5wlgx7mil":"jmcgraph"
}) // 2023-10-21T15:20:31.538Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
