var jw=(function(jsonp){ if (typeof jw==='function')jw(jsonp); return jw=jsonp })({
"2y3gakc4cpow2bnd4ce2lwob":["jwodesigns","JWo Designs"],
"36hqmqnhzo6bcvbckgf6pw2q":["jwparis","Jason Walsh"],
"47eusnoyctvohnzd2wn3dajg":["jwarrenhauser","j_warren_hauser"],
"47rbdfuzta3tz6izdnvj2d5t":"jwatson",
"4xfoqjvaeicya4gxtnb77gqy":"jwellenhall",
"5mj37scc6uu6x5c7scoakpot":["jwar","It’s a Wonderfull Life (Exorcist III reference)"],
"5xi3w7gsvvixosvk7e74cyyt":"jwmuk",
"67x4cstgixflyw3tif7m7yal":"jwcartoonist",
"6ipd2eyagfdhnsz2vy5avi2g":["jwietek","Jonas Wietek"],
"7gm5lwm2f7vgtbl56ii4kvrn":["jworrellwrites","Jennifer Worrell"],
"7utp2kxxng6644bh52rp2klo":["jwordfish","Jordan Fish"],
"af7feejky4xghl222tkhdl4u":["jwoody907","J. Woody, MEP"],
"aleaeewi2hkid6ff55gxc3j6":["jwomack","Jwomack.bsky.social"],
"bcrh7ngtbce7zjwnbfsqqv2t":["jwlm","Jewel 🪬"],
"bdabb7bw5efvwk6dq4xur3xb":["jwatte","Stompy Robot"],
"c7m6ai556zce2lt6c6i4vbjg":["jwcartwright","Jasper William Cartwright"],
"cxjcfouf5aqbdomolsnq6lt4":["jwbn","Bigby"],
"cyymakz33qct7cnjhgh5qg6t":["jwlockhart","Jeff Lockhart"],
"dh6psagwb6m773im3klejnuu":["jwjones252","Josh Jones"],
"dmkc3gidgqdqoadidlwkh2hh":["jwnickerson","Jason Nickerson"],
"e6dcye7blgoj7c6f7nvuweze":["jwall","J"],
"eh7dwg3j3obbuegxhublykty":["jweisber","Jonathan Weisberg"],
"fh2j3d3zw53t4jdl4ouswmhr":["jwnzer","༼∩☉ل͜☉༽⊃━☆ﾟ. * ･ ｡ﾟ"],
"fppwhkikoyvevvtlpqiqtj3b":"jwluch",
"gvzkdtsyo6acyy6vfnr7kexq":["jwherrman","John Herrman"],
"ijl542e5xu6ebu22v6djqljq":["jwink","JWink's Thicc Emporium"],
"iqp3vpulqmfdv6zynu34ci3s":["jwhite0126","별자리점"],
"k5iljqtzjxcinvcpivv7id5z":["jwst","Jimmy Thomson "],
"kg5duhqa2lfoska5kdyyqkyg":["jwolfe73","Jes"],
"kobl5b6edvzpg47tkywemnuw":["jwash","viola davis, my stephen king 🎃"],
"koo5i7vktxn6dqdfqedszij4":["jwatkins344","Josh Watkins"],
"kqir6t6qqcl63expnz4s5tuk":"jwupf",
"ksclhlv4bgof2yofvowcsfqf":["jwarminsky","Joe Warminsky"],
"mgx6fhbize7buww5v4rifgxr":["jword","JWord☭📕🏳️‍⚧️"],
"n6pvmpq4mpegbky334vdk64l":["jwevans","Jordan Willow Evans"],
"n6pzhxxauxd64icofia5il4y":"jwalker",
"npe4ywwpnr2o2niderq77sxj":["jwaughcsc","Fr. J"],
"oniatc35xp7gnlqoytux6n4m":["jwickhyoung","Joshua Wickham-young "],
"ovd4yosoobsdxwmay46wzhwx":["jww.wtf","Justin Williams "],
"p6rnmzmuvz3iuagohmq5km7l":["jwhite","Justin White"],
"pfmxqct6sqpxdhvtefnfcpa4":["jwharris","Jennifer Harris"],
"pxfvx4vln4ui7c4xrfz7pthu":"jwhitehall",
"qa3ymfaji7omtj3soqqq2skm":["jwuphysics","John F Wu"],
"rwy6bokxog4ycqol2qx2dc6n":"jwyoder",
"triivtbcso7kn2vycngk2tjo":["jwdjr15","Jwdjr"],
"u3smqiqgoclp6fi3qbkrgjwd":["jwmason","JW Mason"],
"ubjnfih3baagydycjfiw77mg":["jwedge","Josh"],
"uxkgbxz3co2jbuq62ee77jl3":["jwhitbrook","James Whitbrook"],
"v6v643g7kqpdbmypdaq4edtn":["jwillsnh","Jack Williams"],
"vfkb6ra2lmx664rblalom44n":"jwhoopes2",
"vgq6adf3el2emtp4wmjti7cr":["jwoodgett","Jim Woodgett"],
"vklgj5gvvidkyjp2vj6f4a2b":["jwlewington","Codex Occultus"],
"vxev5od7ub7ppwwzkm2bnvht":["jwgagne","Jim Gagne"],
"wormspkydfe6nx3bh76qaccc":["jwfr","Johannes Waldschütz"],
"xybcnnugj3omzwfzeuzdqkhm":["jw.xyz","Josh Williams"],
"yn56zidjwyuguzyrbkzo67su":["jwr1ghtbra1n","Jim Wright"],
"yznzmyjdhchjtidcnzvriabo":["jwgh","Jacob Haller"],
"zge4qreabzux6inxtldzqw6q":"j-w-t",
"zkarjrsosb4cebr4keqiwm6p":["jwahrenee","Joi"],
"zuxyjv6qlq6uowlzr353b3ly":["jwbash","Bakucario"],
"qh6nq6un66mja733dix3ggk2":["jwang","Jeff Wang"],
"d256kyw6awduvbtnvluso2as":["jw.bsky.so","jw ✳️ ERC6551"],
"jx2alwkav3ndgb43z6hd2fpy":["jwuann","Juan Vargas"],
"u2lpprhvgtwbkmbphrsf3pnw":["jwdng","Jeff D"],
"75qz7tcptqtzv4xlmz25dtxa":["jwbreede","josh"],
"j3sbxjtksrzzmwfwekfpvsmc":["jwd73","JWD"],
"lgdejnavkiglqslecvltbkhf":["jws","Jordan Ste. Marie"],
"g5wbcikfjdgp2kormxx746in":["jwb","jwb"],
"nohozcpi42ou3yttxvkmp64n":["jwl","Justin Lin"],
"vkswdvvp5mt6fwb3kdyhivtl":["jwithy","Jim W"],
"ci6ae5acsnmiiunznmilszsx":["jweb","JWeb"],
"mvqayooxi6n5sauejkcn3tfj":["jwilber","Jared Wilber "],
"k4uo64wez3jkvvhax5swhibo":["j.wieche.rs","Jens Wiechers"],
"xzzrmwtlswyzt5nz4vhmpzgx":["jworst","Joel Worst"],
"5fhhvx5qqz72rqo2jqwebrvw":"jwd",
"elcxkctftlbyjmhtg6ywdlkf":"jwd.jwdavis.me",
"ficsiu554ertjlknl2jgupk3":["jwmoss","Jonathan"],
"ah456cvkffpa63hadlsq7eea":["jwalke","Jason Walke"],
"5bxeiy4d5wje6kslhc6o5ckv":["jwhelan","John Whelan"],
"fkilkf4oovwuvw2dwgwcpldl":["jwlicinio","June Licinio"],
"6takmkl6bn6gmfuovdeyocej":["jwoodward","J. Woodward"],
"t2i2w4vgrbgrldhl3lf4onjf":["jwp","Jeff"],
"njxcscm7gcrfrimdx3d7vupb":["jwgoerlich","J Wolfgang Goerlich"],
"ygeb54y2lfqyi2ssiidkhrdx":"jwr",
"y4tts7l5e7sx7gh7wl4r7nhn":["jward","John Ward"],
"vhjaqiiwhlmort5wbgl2qvcj":["jwright","Jamie "],
"zhu32ozcoimui3erhfv5vqa7":["jwoglom.com","${jndi:ldap://🌃/cn=James Woglom}"],
"jiqhvqeexrext4yqtzdngvej":["jwhiles","Hideous Kojima "],
"alqscsadplhx2iewtiyhoart":["jwaggo","JWaggo"],
"vubyfvkkul6tv2kt5j3snzod":"jwthewes",
"zhqy4sxefy6zjyh77uioh4rv":"jwilly",
"7ktahielbry6hyaenlkxitae":["jwilde","Jon Wilde"],
"s2aktsgm7trvtu73wecsfogh":["jwlindl","jake"],
"gr44ycv4h7dved5rntor2und":"jw1980",
"mlm4hzrailzbpu5x2pi6j5fu":["jwaschuk","J Waschuk"],
"ecpbeckmcr2536losz22vr2d":"jwolpert",
"m4olegjsosxfarhyxyracgd3":"jwesson",
"b2kqh4o5mzzwdhcu5pg3vepp":["jwardell","Josh Wardell"],
"5qy4ott7hnfvslviqxw6xgxy":"jwoeste",
"ykvhnjg247tvm5caoa5knhcr":["jwspangler","Jim Spangler "],
"uwv5wkz6hj7u6gaqc2jrmcgs":"jwalcik",
"z6pqprfxam2bsisnoouiapgo":"jwyck",
"wik72yxhsrsf3f23vvgvylww":"jwm1999",
"fj2pq2xqoduekonnxjwyizpb":"jwthiesing",
"woiedfvgn5goakep2zbgttj7":["jwz","たいすけ"],
"rbohebf3ljfdifjainfh66nn":"jwhuff",
"xb4af57oaq6q4qbotpj7psdq":["jwsc03","Jared Samuelson"],
"b63lvd467wz5hutyjcqxj7kn":"jw1981",
"z4z5aonexzl5ghtj5wkurpi3":"jwlee98",
"6ajhud2od47aolrpi5hwrk2n":["jwrdan","zyo zone"],
"b73x6bszt7radf5y53zguznv":["jwissels","Jasper"],
"g3a7t6uf4pacje4fbtm7b5dm":"jwallace",
"mskqrai54j4chmaangc5xlcw":["jw2","밤"],
"uzig4zfenzwhw4c5jnsouyte":"jweed",
"3ptqmynd6pb6uefucsajexri":"jwillz",
"gzqt55h7ha4qow3fteutctwt":["jw64","Jeremiah Watts"],
"mwpgl7s2uneg2l6yrkkxtzqc":"jwhuidink",
"x7qpjibohp5pa3dtdps225dw":["jwheeldon","Johannes Wheeldon "],
"uaixnfr7opi6mti6kql3jg24":["jwilliamco","Joe"],
"zwu3qccnbgp2474h7m7b6htz":"jwilk4",
"qg5fklvrbydmyn2ndycanlkq":["jwinstanley","J"],
"pwdmmgyptaa2ybih6rixumph":["jwcroxton","James Croxton "],
"aszzatuflcdstvnhewtfy67s":["jwal22","J-Wal"],
"6m2gzhknlh6q43e7mwms2ybf":["jwill","JWill"],
"ufuc2pbrllbma2kxvqk2isar":["jweidner.com","bucketAnimator"],
"pg5x4ip7jgc2kbib72ifk4ux":["jwrght","Josh Wright"],
"xxdwuxz4xtxm5v3f7gko27eo":["jwynia","J Wynia"],
"a5ht4kccceqxqohfkottokzo":["jwlii","Johnny Linnert"],
"gwgelwzb5hlisjljbaj4ecpt":"jwon",
"qymqswahzgo57g4nsmlgrkwp":["jwoliner","jason woliner"],
"74535bxkctfpygubpa5mgcpx":["jwakedot","Wakedot.  🇵🇷🏳️‍⚧️"],
"3atbglqxzrjjkpus4jla5gin":"jwitty",
"ccyotviq5k3xcz4aspyepshr":"jwestra",
"ggirk3436ojpeuptvf2yjk2e":"jw5783",
"mwifpq62hnfzqufa55juqz6f":"jweldon",
"n726udgs4nu5mwqzqrp7pcfo":"jwu",
"pioazrnmlwh4sxu74kqrf24j":"jwells",
"fkgkusraokq2423tcrwjyprv":"jwillensky",
"ismigcgz5faw4ycv7sxtblsm":"jwet",
"imcgxq36yjfybslphndlgjoj":["jwalk","Jason Walker"],
"oxfrvivp6th5mmlsunrozdvc":"jwoldan",
"t32zyqako7ax5jvy3f3gzrkw":["jwolf","Joe Wolf 🌈🐻📷"],
"ri2m732pi5eynzztfmr6yqtr":["jwapplebaum","Dr. Jennifer W. Applebaum"],
"hfqrcts5b6ndfzbher3vbyqt":["jwan","جوان"],
"if64guspyp4zrgksefv7dfkm":["jwrbrtn","Jessica 🏳️‍⚧️"],
"uumz5pajefvjt7r3guized3i":["jwaaaap","Jan Willem Nijman"],
"pqq24xc535zpnhwbf5ch5ffx":["jwrubel","Jim Wrubel"],
"matmf4b2mws6kmbdz4upnlhh":["jweslley","Jonhnny Weslley "],
"pwg5ghj7oa7zrlqwlgfm2gzr":["jwaitforitp","Pedro"],
"onhan4pgutuv3srv53cfalrk":["jwolf22","josh wolfer"],
"umhqgmgwj46e5expb5vzshzi":"jwmanning",
"442rrwyo5dqubjnv4i6afdgw":"jwonderland",
"62b22i2rnxnyzposnxbe624r":"jwfrosty",
"sdvuljdv25ouuxz6n2lek5yp":"jwdrahmani",
"tx6ruehl5y73pfq3cyss5kll":["jwt","Jonathan Thomas"],
"qicf7zxtqvreqzkldjfluees":"jweiss",
"lsupwkalbuydff762ouzvt5j":["jwhdavison","John Davison"],
"sf7xlxocplsm336n7qztad4l":["jwakey","Joe W"],
"37kabez65foowk6swbzqixr6":"jwiersema",
"ji74674q7rkka6i7wedfdi24":["jwa","Joel W. Abdelmoez"],
"scfvvfjabbhkrhmxnfsr75ll":["jwdreisbach","Johannes W. Dreisbach"],
"o2jt66n5afmkifydrguthqui":["jwaits","Jason Waits"],
"4weetluvxztjekstv5c5o5q5":["jwiimy","k"]
}) // 2023-10-22T08:17:19.889Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
