var sg=(function(jsonp){ if (typeof sg==='function')sg(jsonp); return sg=jsonp })({
"2kjiesh7yniik6e3fhfdslkn":["sgtpooki","Russell Dempsey"],
"2kvbamgv3gazaj4bguvgsdw3":["sgonsalles","SGonsalles"],
"2xuiewsf5p6l7kewo3q3mw4i":["sgerrets","Samuel "],
"3d4ysxmdwgpnjgk44xjrchad":["sgcxb0","sgcxb"],
"4phg43l7jqybfn6uebuq7h4g":["sgrif","Spooky Sage Griffin 👻🏳️‍⚧️👻🏳️‍🌈"],
"5hhctv6refq7sn3ztfzwyfq2":["sgnny","ябко"],
"5ukbsaezuyenbntsbpnxhlco":["sgeorge","Stephen George"],
"6344j622mpdkf6fkt4y4eola":"sgadarian",
"6lejno6l7ybshy3c4lri6azs":["sgtfruity","sgt. fruity"],
"6xx2nct3bymmuz6giwatgoxf":["sgtpigeon","Sgt. Pigeon"],
"74o6x7q4ofkr5b6kwb7hvqh7":["sgaarder","Sverre Gaarder"],
"7m2n5dzn6gl4khyvyyc2axxf":"sgmaus",
"7zidv7xpigrhpwx3bim7yzf4":["sgsy417","閃光"],
"7zjlvbzvywglrtywajfpgrlg":["sgcarney","Scott Carney"],
"a5kkp4q3cjakeq4ttqn5q2c3":["sgtopie","Sgt Opie"],
"bftbdgcbe4zclvpkboe4hleq":"sgo.to",
"bn5fxe352m3zsfoiswbyxrsg":"sgns1990",
"e2c4bpkd4bzqcrkcczbwuer7":"sgware",
"e57tihiqkyperjdu7lg66mai":["sgerbwd","em"],
"eue5secfvgr6bf26nf64j4xd":["sgozlukaya","Serkan"],
"g6sw5yagfjtuxrzrmj2oju4j":["sgarczynski","Steve Garczynski"],
"gjg3og3h6ctxa7gls7jszg56":["sguillory262","Sarah Guillory"],
"hc7dsg6vsdcnvpxwqg5wizsb":"sglh",
"hikm2mgdcyiscrynt5w3nr2v":["sgauthi","SimonG"],
"hyjszvnskjuw4azdtcjnhjhb":["sgracious","sara patalógica"],
"ikh2mbrldsuhvrgvbp3xwxzk":["sgpoet","SG Huerta ☀️ "],
"k2pqm32t3kmey32xgs2zg7gs":["sgj","Stephen Graham Jones"],
"kpidzldfi73szwqd6wfxtdd3":["sgriffinauthor","Samuel Griffin "],
"l63ggv5pp62ubcw7k6knum2i":"sgthapablap",
"lbxo2npfw33e6e3vpzqki5dh":["sgulgoz","Sami Gülgöz"],
"liqonmewcdjmse5aysbk4qd4":["sgtangua","Verity"],
"lqxnioj7mtetspbain3pl5ud":["sgcamila","ale"],
"m73dm4bpdenaxh3kwgzk3bk6":"sgtginger",
"mbyc44dftnylsmruqycd3o4n":["sgartner","Samantha Gartner, PhD"],
"mrsmarxaoy6n3freb42kj6wm":["sgtangry","The Roulettista"],
"ngonzxmx4tr5thwhed66zrd7":"sgegonzo",
"ownnibpqcdvoub66n2dxn3eb":["sgcfella","SGC Fella 🇬🇧 🇺🇦 🇳🇱 🌻🍿"],
"qrjwpfxzyuw67cqzsv3nfo3x":["sgediting","Dr Susan Greenberg "],
"ro34t6uptrvueyyabfl6aegc":"sgathan",
"rtoj4e5msh4wbfox6l7zdove":"sgrk",
"sbijswo6z65udtx7kwfcepab":["sgibbings","Scott Gibbings "],
"stviqnamhtkz2dmjw6wwhxke":["sgollance","Sonia Gollance"],
"syhpgw6jf4i2mvvgyth4l65k":"sgtlotte",
"t3ileqzhvkwialpxk2qlqf6b":"sgtm",
"tcoq3cg66pwtos2wsmymcunn":["sgoetter","Sara Riess-Goetter"],
"thquvbctrbyoexkatjqxekao":["sgreen3","Sam"],
"u2y3choy53ofucxfqxgjpenb":["sgfuthey","Susan Roubaix"],
"ui2ny3klqd2movwx52udrvce":["sglassmeyer","Sarah Glassmeyer"],
"uif65qzb7auptgzhgybeo7ct":["sgoa.st","ＧＥＲＧ"],
"w7kv5y5b5fal3jmv6rduawgq":["sgtandrews","Sgt. Andrews"],
"zndoowkiqdcwbyleye5aguqk":["sgtdandelion","Lisa"],
"zv5u27266ocng2mbcrzc3dih":["sgniwder","sgniwder"],
"fwllf4jeovs7i3tdntx2z4yc":["sgodofsk","Steven Godofsky"],
"ws2xxrmhzlno4rovuyiopzke":["sgoel","sid"],
"2weru3pmwbkxboihudlpxobv":["sgvj","UrbanClone"],
"kpb4ykyif2kulkq3wnlpox27":["sgr","さとうすぐる"],
"lvnkad7iosxdwdxl36okdrvi":"sgrol",
"wfsdeasfhiu4smvaoc46dakm":["sgates","Scott"],
"qcnhxpkje52hcasugcnzsnhl":["sgvinip","vini; twitter: sgvinip"],
"mmtejyhcbvqgwsvx23to4z4c":["sgthamsteak","SgtHamSteak "],
"ok76slzvi2qpsyqqzgejckdb":["sgclark.com","Stephen Clark"],
"pjor7cvhfugvwyh34ou2diah":["sgebski","Sebastian Gebski"],
"zc3liwjxza2gwspmf4rgmvqo":["sgreenwood","steven greenwood"],
"gzxa3v4ibhkm2tbygvrznerl":"sgoupil",
"6yomdhq2flqoj7b57ksksblz":"sgb",
"6qan6x3ijkh2qb6xtokjjqn3":["sgnkmr22","suginokomura"],
"32qh6be2yv2cvgk2u6w2dhtt":"sgerogia",
"tcnhunin6rtlcqqwtzxnrrif":["sgc","SGC"]
}) // 2023-10-21T20:47:44.270Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
