var vg=(function(jsonp){ if (typeof vg==='function')vg(jsonp); return vg=jsonp })({
"63plw7yqvr7ewvxc3oh3j33s":["vgoldsmith","Victoria Goldsmith "],
"cq2t4el5p5qxnb67cbejwdzl":["vgm","Vini Morais"],
"eic3pg6fy7gdwhues5i4ecyv":["v-greyson","v. greyson "],
"hl27uzbmikqn6rmdb2qmguqy":["vgarcy","🎃👻🕸️ Spooky Viking Vicky 🕸️👻🎃"],
"itms2ffcmeplgcbbp7ilhdqx":"vgautron",
"jcwinktdtx5jokfbbfwzwe4a":["vgdropout","VGdropout "],
"jfakh6smiea4oae3rjupaiw6":["vgt","vgt"],
"jqv2hwhmiwp7rwgsiuqre6vl":["vgcatano","Victor Catano"],
"l2u34pyxepcombpqyxbhzgy3":["vghistory","videogame history"],
"leh7c4pdjaowmugwggfsjthn":["vgcartography","Max (VGCartography)"],
"lql24sh4bz3wag6pcvtzbdba":["vgonly7","Tarnished "],
"seajq4u4d2eftbjfumivwiwj":["vgaxol","Axol"],
"tm4xkr7gv5pzyq4dwirch52o":["vgfeather","L. G. Plume"],
"vfutz6zl3mpx2oyczksscpsy":["vgmuseum","VGMuseum (ReyVGM)"],
"vhptwqh6db73662hlxy3xgqm":["vgplaysgames","VG 😎🍌"],
"xkzgysgrsns6f26uj7sbqnku":["vgr","Venkatesh Rao 🔹"],
"xndvyx4wuboggxmzygmkjtss":"vgdvgirl",
"zymiavmtif2rj5oklzyzslpu":["vgel.me","thebes"],
"wxoiticpe4npourj4v57tnw6":"vgo",
"mtkioe5s6zt2f7nccptzdajk":"vgoklani",
"rmkgeupdrnxrd45j2bfmvemj":["vggonz.denibol.com","Victor García 👨🏻‍💻😸"],
"7pfgucgpi4n6wphjj7atcocc":["vghaisas.com","Vivek Ghaisas"],
"fczhdojtvbplbw2jyqz6sf76":"vgc",
"n5w65wejudcrf5dtyypdd4nv":["vgurbuxani","Vishal Gurbuxani"],
"bqettoxwotmyfkzigccjlnuv":["vgrafe","Vincent Grafé"],
"4yn3mmbqfth2zqawjvixan3s":["vgracie","Victoria Gracie"],
"mmencbhkaifzjx2fkqmctakw":"vgv",
"jux6yqtljiri4gkujw575ip4":["vgsn","しあ"],
"fzwk6x4xclrkcubrxf5o6yn2":["vgokarn","Varun Gokarn"],
"5lzsxxacx4dgp74ngywe54po":["vgnsh","Vignesh"],
"hrbcyzifs4efpv2c7c37myul":["vgwschutte","Virginia Schutte"],
"5jaeeit7japwlxqoaablnbft":["vgatwtoe","Video Games Are The Worst Thing On Earth"],
"y56zbvox3fgvkisvbxmjvblu":["vgrasta","VIBEGOD"],
"qiaq7fvuubaq26a7442apxdn":["vgc.name","vgc"],
"innxj5xmb7n5lu5ohzisin5e":["vgandhi","Vikram"],
"s3o3tggee5vrs5rwzr3zdism":["vgoldwasser","Ms. G (she/her)"],
"xh7x7szmmksdst3vwixn4pkw":"vgaran",
"npmydpmb3owv4tlolodlmsmp":["vgadv.com","Video Games Advance"],
"sdohlq3iqvni5qbi6axavop7":"vghrk",
"2q4b67yus2ps7blkjpjgscnq":["vgraphics","V.Graphics (ꜩ | Ξ) 💎"],
"l44iyhgbgdnzelrsgtr5jjjk":["vgenealogy","V Genealogy "],
"kkswyls3hff2nwbz24j5ioyu":"vguerrero28",
"udi5cqdsuhu55agzykpvmdgv":["vgchronicle","VGC"],
"wpco74ry7mlsr3ama2zidwds":["vgirl9097","Virginia Jones"],
"wmbpdiznsus5ibmumxpo5vsb":["vgiangrossi","Virginia"],
"cilkib5mr3um4j66pnzib4k2":["vg247","VG247"],
"mxmfl2cvaywkc36qb62olmxf":"vglorioso",
"x7jqg77lqp7r3jlxgf6hnj3w":["vgolinka","Vladyslav Golinka"],
"cmtughn3er42x537t3qwsyr2":["vghn","Andi Vaughan"],
"fadsghddlwducw6aopnl6flr":["vgga","VGGA"],
"sgm5g2dhscwc7q54irjsshjv":["vgutierrezvlc","Víctor Gutiérrez"],
"k6t4kyuhpeb6san3kh5vm3ok":["vgarcia","Victor Garcia"],
"m32c55ta5ic7myhrkjrnnyj7":["vgilbertauthor","Victoria Gilbert"],
"e5bui2dvlhbbimbyg3aeaapd":["vgutv","VGU.tv"],
"acppqe2ohv2qsybxcrhsy2kl":"vgp314",
"nvqn23tpaavbbqp4akuumwnr":["vghaiku","Video Game Haiku"],
"odx4fpt6s5ekfxsjeecbx2lu":"vgg",
"h254lri5kbpxzoyinpzaqnkt":["vgmmood","VGM Mood™️ of the Day"],
"7thwbvs7uvxvmscncdqkqsmx":["vgx","vgx"],
"f7dnafolppjgbdhmwpa3y3uv":["vgn","Marcus"],
"vy4cw7gcc3acof2263a2rflr":["vgabriel","VGabriel"],
"h4m7lmxynrs5ftapbpwchddg":["vgacomedyshow","Video Games: a Comedy Show"],
"rn7prxahmrcfapuokk3ri6y7":"vgvikdal",
"6x7mbnbklhmlsbuviugvxfin":["vgoralex","Valeriy"],
"r3ex423si7c25zyfc6o45ifa":"vgrd",
"apxl5qpmnq7sgk5lk3fmca3z":"vgdostrow",
"wndy5ftfycir3fe4n7xyy5ta":["vgfromthevoid","Videogames from the Void"],
"d2uugsr2axyppnd4hei7qogd":["vgkoch","Valerie Gutmann Koch"],
"kjnnwadylmr62wfnwcnecase":["vgdensetsu","VGDensetsu"],
"obrnjrjbsopw4uhh5mykmwix":["vgk","Emilia Belle"],
"xoczhhwmhuvtyzntdn5yk6it":"vgmaps",
"pb43eaxvflzb65sussncrx45":["vgaltes","Vicenç García"],
"ilo6h5jna4s2tg74i4auhsxr":"vgfm",
"qosux6sa437zinjqakpdd6mk":["vgcaldas","Victor Caldas"],
"q7nv2zx6xlczuap4rmwg5jnm":"vghastly",
"vwrcbiwrxp4w3dhk46dkfu62":"vgt789",
"ufnoydfdg6phatibv65hkgmv":["vgets","Video Game Ethics, Trust & Safety working group"],
"clcuivdvw3mstz7q5vy66iuc":"vgcollect",
"to4bmtjchei4gakweslu365x":["vguria","Víctor Gil Uría"],
"ugw4z3eawt7zaosvhknzdjid":"vgkmike",
"n7pebf263mdisdipz4wfepj4":"vgcoutinho",
"3lefqj4jzx3iaj6wwy75kgwj":["vg584","VG"],
"6ebb5m4nhgp2k2neyolen2b3":["vgshea","vgshea"],
"5bkj7k6rl7oytmmvcdrj3pw6":"vgsk7",
"2rawqm6wcqffhm4awmg2f7jo":["vglitchv","r"],
"b7yjz6gl3qoywwwhvn7ldlal":"vganesh",
"7qa6bpbcoivy6arytdabacpa":"vger2",
"vg7xquz7wrsdg7iqcqphimh6":"vgkallday",
"tw5gu2pbwblir7exowfix6oz":["vgbraesthetics","video game bathrooms"],
"ls3527rpfry3mwsv43xuslyh":["vgapocalypse","Vidjagame Apocalypse"],
"5bjj4obw2i7mojnu4ueeqeed":["vgranucci","vgranucci"],
"uis4xkbitvhdjkiqpb5vifb4":["vgknight","Virginia Knight"],
"hqod4dkcejtndpgp6xub5gw4":["vgnlaufenleben","5andra77🌱😷"],
"o7qq5ur6jgx36lcw2jhhmumv":"vgrabia",
"ihedb6o4ssu546tgerp72ya3":["vgebler","Vance"],
"3vw6mbtkkkv5ov6scj2wkftg":"vgardner",
"v64z26jr5tpkhtmpzxapbbao":["vganimated","VGAnimated"],
"lcpkkbni7mu7cvjinouorxxe":"vgorroz",
"kguruodfx3flag5j3ij6qykf":"vgnsocialtest",
"ngh7aiy6y7xg5ah3jxgkttqi":["vguerra","Victor"],
"humgs2laajn6g4y3n3dbadsf":["vgford","Val Griswold-Ford "],
"wpqrhm3b2wcd4baot7ojvoy5":["vgnesis","Gnesis Villar"],
"cgo76gdtgpogafjwsd22zma4":["vgoeoxt","오만둥이와편육"],
"wiu5bt5qmsio2n3xolepzakk":"vgkid",
"qiqy2fpzn4zei5qst4op6usm":["vglogoarchive","Video Game Logo Archive "],
"lhbbd7y4ni6zozilrrsmd2il":["vgarou","Vgarou aka Seb"],
"kuprqo6kqyspwkmtfqwsldkn":["vgranosalisv","Heisenburger"],
"om5e6d7uokih2kkjpetr7ebz":"vgsouza",
"rextlparbd5amycxd7jr3rg5":["vgelfand","Volodya Gelfand; Northwestern University"],
"ks2od4dwnr5dqx3xaf3zd6ug":"vgal",
"3gjtmilevs5fw5uqik3bewmp":["vgcake","vgcake"],
"zxooflhm4umj57n7mmyh5jqf":["vgbhieel","Vitor Nascimento"],
"ax3rvpuzmafdfi37zbuhjplt":"vgotaskie",
"tsuh7pk5g7wqn3nnc6rxkpod":"vgmtogether",
"xk5fdmojj6y5ph4fg3dkqd2l":["vgh","V.GarciaHuff"],
"2axufkkviaujmaz4sqh7b5tc":["vgfilducci","Víctor IlDucci"],
"ezlvan4uppp5qs6vquwrmo3b":"vgobarnes",
"nffxwlgs2vm7cottbugjilv7":["vgkknights1234","VGKKnights1234 🏆 (8-0-1) Aces x2 🏆"],
"pngt5zaie6mexffpihesndee":["vgdg","_Професійна_хейтерка_"],
"543q3p2drzss3a4wrbo2dpmv":["vgafanatic","VGAfanatic"],
"iqc32yx2edg6vp3seqiou2pw":["vglaceon","Vlea 🍰"],
"x4g7aerrsxh66snqtd74kenx":"vg170",
"2yid63c55twvhrhrwtsbt6zp":["vgobservatory","Video Game Observatory"],
"xhuvpallb5c5ss6yu6cs2gws":["vgeshkovski","Vangeli Geshkovski"],
"hui4fj5glyfmesivouyzno47":["vgcheeze","Cheeze"],
"j6pbgspzabctz6v24p6os4lv":"vgl",
"wwjodlajdr2h76duuwxwe2sw":["vgartner","Val Gartner, PhD"],
"j4gozqdnmxtxmxjnrm65bzfg":["vgeermcgrath","Vicki McGrath"],
"v2qdyho5bypfaeuunxeemrc7":["vgnysoft","VGNYsoft"]
}) // 2023-10-29T16:26:38.284Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
