var oy=(function(jsonp){ if (typeof oy==='function')oy(jsonp); return oy=jsonp })({
"2hxnaryilszltnna7vlsllsu":["oyasumiaow","bad vibes only"],
"4cmy25fjdjgqshcxfitxqbxy":["oyilmaz","Ömer Yılmaz"],
"6hogdfmjxtqkbdoi6h4gl7jr":["oyasumilunachan","luna☆"],
"6tiydzw7nyhby4errl6zjhli":["oyrou","Oyrou"],
"a3d5grerapvhtpdzn4dqrd2i":["oymojo1981","Mojo Jojo"],
"ams4tuoyhtxnerzztgbzwxac":["oy1385o","Цитринка🌱"],
"bqalaoacqc4kmfvacjhvqzfd":["oyx33","🍍Fruity Kenty🍍"],
"cdu6ydvzc2pubg4rozs5u4ch":["oysta.au","Christopher Owen "],
"dhoserd6jgsemufmiply6jej":["oyakitabero","おやき"],
"dqsphfr5236yni2n63c67dpw":["oye","OYE"],
"gfpukluqxfeg2dwtf2mamxfq":"oyebilly",
"hi5gfxjzuvlvu5hueu3oxuoe":["oyendraws","Oyen"],
"lhr6brlshro2wuqmfqsmiqhb":["oyatake","おやたけ"],
"mo6uhnow7qhlj6abtiqzcvhk":["oyin.bo","Mihailik dey"],
"mt63fm2icdmkjo25lygvcdmn":"oyasumiruby",
"n7wz7j4rmdamygsporjruwpa":["oykuc","öykü "],
"npmezypnkaptjc5rzd6fnxp7":["oyc960819","CHAN"],
"ojisjnfrxszqkqvqsjabh4oj":["oyveybrodsky","Double_0_Snake"],
"oy6ymdc6me6vbef3kmgou6zp":["oyoyosaigetu","さいげつ"],
"p7uhf2ibx6ptclg5m3vmbqao":"oyvind-wedoe",
"pfnsi3lwnxml2v53np6mhd7r":["oyenstikkeren","Elen💜🏳️‍🌈"],
"pnbuskya3mep2jkcycshlsfz":"oymaxez",
"uy35jiq7tnmbvf3hmnmd6q7o":["oym","Mark @ Own Your Mark"],
"vfv2npnifqsdj2cfgmnwyqqw":["oyvindhalsoy","Øyvind Halsøy"],
"wbr26zfh35jfbskyz3en7csx":"oysterboy13",
"wmn5xvumevjynhzmj57irbju":["oyunomad","🐿"],
"wtl623wctej7mnjlzpmtb52q":["oyster","여오이"],
"z5ftjw35fxakdgxgvvq4jkfm":["oyatsu","Ytk"],
"zgv4cyzdzm2zzpz225khjyhf":["oya2suki","おやつ。"],
"ypwqtdmznwvfxedadyvaxyvf":["oykusenlen","Öykü Şenlen"],
"de6r5mmi4ixjomdc7oxymzgs":["oyvind","Oyvind Solstad"],
"zbtu7rlb7pnjjwyy2o3tlqe4":["oyisands","Oyi Sands"],
"5im763wgfmwtkcmz3mteehm4":["oyoungzin","The.oYoungzin"],
"i5dvzxj3xwrnwkvsr2xrrhgo":["oyabun","Javier Alonso"],
"f7ts5x3rprwqbws2dy4lhezg":["oyousef","Odette Yousef"],
"7jjxb22fkl6e6fea6ya3kjay":["oyinlowlah","Oyinlowlah♥️"],
"dt5ymm5xjyvcsavrfrjs4sor":["oyzk","おゆざき◆OYUZAKI"]
}) // 2023-10-21T20:54:58.184Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
