var dg=(function(jsonp){ if (typeof dg==='function')dg(jsonp); return dg=jsonp })({
"2i436xmthkx77jhstruxjiun":["dgrand","David Rand"],
"2q2dqgjb52iayhirdu6hmuls":"dghroks",
"3kctzhzdeiip2e7fmrsfruaf":"dgslvlm",
"3l72ugq3tsp5ff4ru2opgpax":["dgunn.uk","Daniel Gunn"],
"4rjtghvuhmg4wmdvmktze2td":["dgrigar","Dene Grigar"],
"6hlyu2xpnneo6632loyapnjd":["dgb","dgb"],
"7bwzsd4tsecmzkd3vxsjyk6v":"dgrnbrg",
"7rbrad3ncrguw2so6bd5jhyc":["dgarbe","Dave. Shiftless when idle"],
"anzslcuo3cz6vpg2rr5y3i3c":["dgm","aspen"],
"aqq74uwjus5l7lue7ptgqch6":"dgronnes",
"awi72cidpj3gfthkztprawbc":["dg4016882","でご"],
"bsk6kalsxhthke6mjr7kflmm":["dghart","Debbie"],
"bx77glalf3xevvrsjq2w4zer":["dgbassani","Diego Bassani"],
"cwwgqx4mj45lhhezfts2trss":["dgp","Derek"],
"d2os4r4i23va52jy4hfsvdbh":["dgoemans","David Goemans"],
"dbeevfkunvxaktfn7dnufzdv":"dgspsoa",
"djznhtuxa6mqmne7s3bpgj3i":["dgoldman","Daniel Goldman"],
"exhq42bme644giyacfnmiae3":["dgfrombr","DG"],
"fjfeio2zz3iimsgvqjyzfppg":["dgaboriau","David Gaboriau"],
"gn3bstmavkjnfhr6jyj4utpc":["dgsus","Daniel"],
"iyfwt6mmbc4l53ic2qunigl6":["dgdela","DG"],
"kiyv7vxcplepqxft4d6qd6zt":["dgraham","David A. Graham"],
"kx4we4kmp2hodtjpx33k6mrl":["dg1017","Designgrumps"],
"lntchm65ohh5mrnba43pllee":["dgmcdowell","David McDowell"],
"mlc6pzuop5takh7fw432vmq7":["dgoodmantrublu","David Goodman"],
"nahxc3wqc4ts4vsbymhg3u5f":["dgschell","Donny"],
"neqji2rntcqeh6lzh5r5o3b7":"dgllana",
"o3tjvixhuuiokbqh6e2we75a":"dgmlr",
"ouiyzkxbxochd4zdp3qhu66z":["dgmacarthur","Daniel MacArthur"],
"p43yeealhoop2uzrlok557jk":["dgh","David Hughes "],
"pos3hrv5c6t4qjxtefok5k6d":["dgrmsp","Call Me Da-vid-vid-vid"],
"pspscvcdzbzqtsmo74fu4jns":["dgcloudrunner","Dylan Greene"],
"q5kmmvj4wzoxqzttg5g7nczl":["dgbrn","Deidre"],
"qgxnofg2rwh3sxufedttkgcx":["dgar","Dgar"],
"qpvrwlghb5cbzpm66jboiqae":["dgoodwin","Dgoodwin "],
"rgcvjzfu7gtfxgkxxxjdgmkz":["dgpishnaiad","کپتن "],
"rsg54qyfos7yxeiaeiolw2bh":["dgahn","안동균"],
"ua2rsqap2q63o4e442pzydez":["dgthizio","daf 🦄"],
"vf4flbjovx7bgju6lgjbejez":["dgoold","Derrick Goold"],
"vjgdpgtm6sbmz32bor42bxub":"dgasser",
"wn6gd2gonytw5guoq5ymeimr":"dgoddess",
"wukbomhznyxipgcsb3sshfnk":["dgtarbuck","DGTarbuck"],
"xb63n4vz277er23z3wjb7zzq":["dgo81","DG"],
"ylossjzuujliuwzoqpfdxsia":"dgo64",
"ifpe2x2kchkhb7z3jxsssh7t":["dgladfelter.com","Donnie Gladfelter"],
"jijwtzgroy76samnivlqrpec":["dgaff","Toilet daddy"],
"2fiv674sr4vniqkk2ovav4oy":"dgs",
"sq7tdbj37i6mmmrodgsmw2cs":"dgzvd",
"pl3yxocwhepkovdb3ufcxyz4":["dgrochocki.social","Dave Grochocki"],
"nmp2xubonlve2t6si65cmpdu":["dgentry","Denton Gentry"],
"stturlgynm3i52dbngsvpiuu":["dgmarious","Marius"],
"axabjwu75ljfbyrv3iytqrbx":["dgogel","David Gogel"],
"jeqcfiuna4enkgdcxby36a4j":"dgellow",
"qq3bobf7pum34mivhxxrq2yu":"dguido",
"fq5sthqnasigjl7cbenzb72c":["dgolumbia","David Golumbia "],
"c5dzeyc5h6ragvlf4zg3p4fd":"dglazkov",
"wtjrt6htsfjmpvbgmfikufta":["dgcandoit","DG Can Do It"],
"zd2hcide45qabwnlmpaiqyoz":["dgw.me","dgw"],
"xjpljay2bpkbbnuy7gkj2onf":["dgreenbaum","Dave Greenbaum "],
"whki7xovndk65kncibmgxk2m":"dgadiwale",
"x4tcmiiudfsgfacs53rlvxqj":["dgebenlian","Dani"],
"yunqbqbjoa4fy4fu4s6ezksi":"dgtlj",
"nqkjv7w4kqb6psx4jwm6ekyy":["dgls.dev","doug"],
"u77uu7o36zb3rhevbhtgoetd":["dgon","Dario"]
}) // 2023-10-21T22:24:57.449Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
