var gp=(function(jsonp){ if (typeof gp==='function')gp(jsonp); return gp=jsonp })({
"2qb2ezlp5enymwhm6eijidoz":["gplusb","Gary B"],
"2u6ecf63f7wwhfnnvfzarit5":["gpkay","Geoff K"],
"3m6jpnml2wdo5z5p6iypyjec":["gpinheiro","Guilherme Pinheiro"],
"4wjwvbj7vv5rl56czaep6yjv":["gperron","Guillaume Perron "],
"5a7rpw4wyo52su3rjrvbmxgc":["gppasco","Paolo Pasco"],
"7unnuqvyphh53fptjkfh5kxu":["gpkanklez","GPK"],
"a5i6wo2uzsihtvgokfh2y2v3":"gp2k",
"acunfj4eeb6stjq2hzjlxzhs":["gpp","GPP"],
"aobmydxrvsjvd2rxol5cmh5x":["gpaulinod","Gust"],
"axkg2q3p4rl4jyfjoqslqifq":["gpharlock","gpHarlock🌈"],
"dbjiujt2w3zq4y44vgdsw25x":["gph","Connor Almond 🏳️‍⚧️"],
"dmh3b4dqqkqjnjsvy34g57b5":["gpte","GPTE"],
"dupzxm7e2owolkhkzwf3zvn6":["gpp2099","The Blonde Magician "],
"eh5nbcztvl5c4xyo4ftfouly":["gpolisner","George Polisner"],
"flyctcqgejwmkyuzzk3tnyu7":["gpijanowski","Gregory Pijanowski"],
"gjs2eeoldbxwvd7ypn6e3jwa":["gporro","gporro"],
"hjykhrtsznz76d4qllrdbywq":["gpike","G! "],
"iezpvs2exb7v66433hj5myzc":["gpd0","건포도"],
"jjvcllmstrqhwumataphanzw":["gpurcell","George Purcell “Punished” on Twitter"],
"lfd4q4nr37apsww4z4eitohj":["gpdmckay","McKay"],
"ma37ez4i3gmwkvwpytsqeepp":["gpsnmeajp.achetaria.com","Segment"],
"mudwhdz4asvrodou2wogw7qm":["gpryder","GP_Ryder"],
"ohhs3alzkrgzrzeylsmeiv7f":["gplowe92","Grant"],
"p2bj3d37m42rqcoqvgrmwhm3":["g-pop","GPop"],
"peiyufadnimuqaj3ubdov44p":["gpmciver","Gregory Peter McIver"],
"zg7lgcxhdkoufwuypudmpjjb":["gpatrick","gpatrick (Tanya Chutkan/Fani Willis supporter)"],
"tdtkywxbgzdblalzur6eeqlv":["gpsnmeajp","Segment"],
"hjmesocb5vs4otqgkqgbp542":["gpt","GPT Bot"],
"wavac6mivpset2gc3xq4fcik":"gpj",
"xoh5i7yo55saptm7kx63u5jb":"gp2980",
"duxmgyr2tlfy7jxc3whi3tpt":["gps","💀GPS"],
"fzcpmja7jfuym5u3dxvj3rgj":["gpg"," "],
"wvkghng6oe3pzky2xigv5hbk":["gpu","sina"],
"qxeusgdjzkc2ncjtncoqnw46":["gpborges","Gustavo Borges"],
"6npiqubbks2wqhnes7pribw7":["gpt.cackles.xyz","cackGPT"],
"sw6usxekmwsmhylwusjjetvt":["gpatty","gp"],
"ghkeft2ux2mmxmuxjd5yf566":"gpssysop",
"wa4bcc7tafxfg6qweyo6fntp":["gpecemilis","Gustavo"],
"c5ffei3sa4hnvvub2qxqzuru":["gpass","Gregory"],
"g4arno6cavupbovixt3xp5ec":["gppeixoto","Guilherme Peixoto"],
"voqi6wk6dyy7lwnzbwtlk24y":"gpt3",
"z2qrjmv4qyuiaicgricksi3t":["gpegsok","Peggy W"],
"4ry2m7iw74i4b5pelux52ism":["gpraznik","Gary Praznik"],
"gnpou7kzovojzv56ytfuewnb":["gps.pro.in","ਗੁਰਮਨਪ੍ਰੀਤ ਸਿੰਘ "],
"b2r6kughszdtm23mpsmrchft":["gprimak","gprimak"],
"sgr44ymsbzis2c5xrmacukfb":["gperrenai","George P."],
"avby7nwp2cjutq72stxfe23p":"gpbell",
"rlvufeh35vdfscqw56x33p4m":["gpknight","Gabriel Knight"],
"t4vyf3ujikvwp5wk6yiqsmim":["gptkrsh","Krish Gupta"],
"sef5ernhijkez2xijfsf72yd":["gpoust","Greg Poust"],
"um4pbeq5oy7zpsdezi3kjofd":["gpunter","Guy"],
"podze56is2jhum6o6tsuhclt":"gps0dvqx9r",
"ojanamekifuigcgxma26bovl":"gpf",
"t3o34oh2bz5aa5pn2fhor63u":["gp504","Black_Apple"],
"lwuwlkh6ixi52wmg6j5himjt":"gparon",
"anyt734ut3qzsao5ts76xmvd":"gpunk",
"ww5zw7im4zyq3tqhcg2tnkkz":["gpdls","헤인"],
"nz4azjqexh2nwelujtm3feoc":["gplzr.com","GJ"],
"bbkk5tgiip3wttqkdh3wvypy":["gpaumier","Guillaume Paumier"],
"ciwzbwegkza53pxeo2f4mc7q":"gpow",
"zpdc5d5hsfecnynq65zt5t2t":["gpadron","Gilbert Padron"],
"43jr7cyhdyn4o27xrax6mze4":["gpm","George Pérez Marrero"],
"s2de5dtoitzfd3qh4krcvsvt":["gpl","ghostopal"],
"6n7slulyibfyfmkqqahkecdp":["gpc.dog","gpc"],
"sz6sjcq7wwl5zc4bet6rrhuz":["gpfjeff","Jeffrey T. Darlington"],
"chtwovi7qhl7zko6umcibgk7":"gpastore",
"pw4zlhlakhvnl7j4kpsp2tsb":"gpe",
"ldgb7hlslzbjfyjlapfe4ard":"gpultorak",
"yhs3ecjjhtmdd2ggbstx3tob":["gpshere","GPS"],
"hink24ttl67hin242jwa66p3":["gpwa","Green Party of WA 🏳️‍🌈🌻🍎🌎"],
"fu2b6vwae7rbuv7x6qdmbvya":["gpessia","@gpessia"],
"6jjw3zxbjzvdvjyegakeug6t":"gpeairs",
"s4t25xmj2cxbevhpzuiqn7vu":["gpaulaeduardo","Giulia"],
"xes2y74vhvnv6kzmpz5osk7r":"gpratt",
"fnlch3w6l4da2mt44awmdzhx":["gphantasm","gooeyPhantasm"],
"5fuvlyr325q57k6zppno4z7t":"gpal",
"7hpyrpfqnezq3vurc4x6cdr5":["gpdawson","Graham Dawson"],
"7ph4egfoalbzgxk5obbwhcn3":["gpinvestigativ","Greenpeace Investigativ "],
"j7oqahst5lrdxfb5eywzkfdj":["gpscorpion","Karina"],
"5je4lf56c3ockstfxwmup3ey":["gpiercecummings","Gini Pierce-Cummings"],
"iquws6m4he4sfhrluf7urbja":["gpoulson","GregP"],
"wbk5toqdeszgjgnf3jywbzso":["gpask","Greg Pask"],
"l3mpxpz3gbtxzyniiwihrunt":"gpb",
"bu6vwp4x2iapsgat54vdfogm":["gptaylor","Phil T"],
"plh23eiwava42sd2c3uk6nqb":"gpatters72",
"x7yyfnvurc4d46ziryw4mf53":["gpn","GPN"],
"nkewv2puna4iedjhht4ur7p6":["gpf-sct","GPF"],
"c43a6xffn5tsxnvellnhzqj3":["gprimosch","Gregory Primosch"],
"kufsggkfkgjcyqc3arulxffr":["gplaye","Guillaume PLAYE"],
"ggnesdfiwil5kuxwchqfknal":"gpireda",
"xzofcx6wws3irdrp4oqupzsz":["gpleonel","Gpleonel"],
"ki2iqcviaaaxulvdstffqr2t":["gpolite","Gpolite"],
"y6zk7kjhrw2rlz3gv66icwt2":["gpluess","Gregory Plüss"],
"o4l5kj72jypeym32cxc6kfyc":["gpeters","G Peters"],
"pcswcjennqos23ykahm6wb2a":["gpitfall","Gláuber Gonçalves "],
"pv3iodyoj4qe5iepe4dbohny":"gpat",
"tvcc5ojyoefba6nrh3fa6mxx":["gpchem","Gpchem"],
"xafziowpelzlc5vho33asgxd":["gpr","Gallifrey Public Radio (GPR)"],
"7ezed2cyciqa2ngbau3myzr5":["gpsforthebrain","Gwynedd Pickett"],
"ydn5k5fedv4fnfblgukg6zis":["gphibbett","Gustav Parker Hibbett"],
"dr3blf7p7b5mz2tpfwwksnuq":["gpsdevice","Chase Windham"],
"c75ggrbnhcfhwzg72abtpdwk":["gpot.art","GeePot"],
"tqmkhvmtcxr6fyradvwvpbzt":["gpriestley","Georgia Priestley"],
"mimdc5lmepug4ys3iq5tv4nw":"gplex",
"wjhitkaqlcipd3a5iac7xdwn":"gpearson",
"k4nmy37xkm2wy4v345gnlh6w":"gpower",
"srpy3hlohjudmhqzbisexlj2":"gpowrie",
"knuyeigwdwkv6nkuht2uffqo":["gpc808","gp"],
"5i3ptcea5rxnu5ihj5sjg5kv":["gprado","Guilherme Prado"],
"yyu2ghhi4g5rljlq5baotzx6":["gpspices","gp_spices "],
"6ydssgsdhcxqsinajheay2xl":"gpx",
"trpt6lwqxage67xokdrdl6om":"gpearle",
"tbns42mff3l5qgxu5hibhlih":["gpainfox","𝙜𝙥𝙖𝙞𝙣𝙁𝙤𝙭 🔥🦊"],
"jhh6t3iuxmrqnb3phlweus53":["gpetersen","Garrett Petersen"],
"ouy5znksx27jrtflvxcwim2a":"gpippin",
"fmdloj6tfx5t252xvh6mzktb":"gpeisen",
"ycyckjorhj3co7odqusomncr":"gpatb",
"sea4tclx7x3crgf7rpathuvt":["gpjt","Giles Thomas"],
"qnl3kfp7sfxafaarcji5hvbi":["gpaolofontani","Gian Paolo Fontani"],
"q3lhx7kzv7brzbxr4wljjrnv":["gpummer","Gerold Pummer"],
"4av4nbd7adpltc3u6tk2csa5":"gplato",
"uogtv7afpakdy2mkhiiqn66u":"gpark",
"dlciwnjvadhpdfqv3ilp5y6g":"gpostcom",
"e7gxb4isozp63png2xxjckuz":["gpanku","Ford Ka Preto 1.6"],
"vf2zkvhrskmnorur6fnheuno":"gphunk",
"adaf7nrao67ccv6zruyg5uip":"gpof",
"pnyrr5q6tkoro5jcjml7yzlm":"gpau",
"vtdvi6e6shlc3hvbley2tvpj":"gpall",
"4m43jblnw3wqtt2uru64plwb":"gpendler",
"hzilr2r36kdscungfd6tmvli":"gpolosa",
"jci3nn3dueijmubxucxkg2os":"gpford1",
"azouvktonpwdx3k5n7uvhblt":"gp78",
"ypji4cqzg5knmqnsbyauu6z2":"gpickle4",
"t54lepsbes22cunyppeim4pa":"gpsm",
"d45uxpusdhwsl2bm46ohjspo":["gpimentel","Gabriel"],
"wq23gpuxcn5bhsh4d5z75ti5":["gpulvi","Gabriel P."],
"gop2fpstubwdmksn3uai63yl":["gprichardson","Gary Richardson"],
"iiwz3spflzirhyvtbmdjnw75":["gpk137","Johnny137"],
"of7j4p6gkhkpp5kqsc77w3cf":"gpc",
"exs3pizzlci57lleosxekxie":["gperry","Perry"],
"inye6wpm6olhm7b2flgyjaze":"gpg23",
"fryzdfkd7k3sfssu52jh4axv":["gpxgp","GP"],
"lcq5dmtcxdmvaqq3cqldg43k":"gpires",
"ffzidlcskclsptlrkojsnuk6":["gpub","Graythorn Publishing"],
"nwam6r6vkizydpm5kxyo35kx":["gpiece","녹색조각"],
"5xqb4lmkdtakkne344zymx3p":["gpybr12345","☕@避難所"],
"q4yqi3opl2wnc4k3n27vylp5":["gpcinc-green","(🇧🇷) Green Nakamura (gpcINC)"],
"f6jkgjqznhnbip7az2n7ffi3":["gpmooreesq","Geoffrey Moore"],
"pri3asybsvnoqpruhdto6cju":["gpjapan","Giampi in Japan"],
"ka3qhxxrwsg4vkts2lcbs23u":"gpapadakis",
"wyjhzasa2eext6qpzpjclkoa":"gplatret",
"2yyswddxgdixsgbpch3cz4hi":["gphinol","Gphinol"],
"bh567e6yaejgx7dtsqdzgukz":["gpedranti","Gabriela Pedranti"],
"r6gwcnfxid4jzuv5xd7juqbm":"gpdon",
"6abmnonfbmqja4v5jvdyb2s2":"gpearsall",
"uavy43e26ufio5ondu5vtkxe":["gposecat","GPoseCat 🏳️‍🌈 📸 🦁"],
"seixzus7rvbqyj6itvpjdjuj":"gpmz",
"cm3bqta2ufycv6uksgx5suix":"gpaes",
"daftunkmypucxkyaq7efu3eh":["gpressey","Graham Pressey"],
"g6zdg6e3eorhxzj3qwbtz6uq":"gpl28",
"q2evtieft3lbmicfdrmhw73i":["gpciczar","Gpciczar"],
"xsg4lm3l6jeo5gp6nrl7iash":["gpujeff","The Graphics Dude"],
"hsn4hwq7yu4pqc73qqmq5qzm":["gparlakgul","Gunes Parlakgul"],
"qg7mra6jgcygo7glebzq3i3a":["gpyaelay","Pyae Lay"],
"v4ga63n7xdakmxuym4xg63zr":["gpoeti","Gio"],
"qyh55iy6pse25zkokpr3h6lp":["gpwilliams","Glenn Williams "],
"6zebaxmsgtdoazu3jgoaodot":["gporterfield","Greg"],
"jayjbohbfmngsxehfhwhwemh":"gpayne56",
"b4sgfzczwvjjhky4pay5xst3":"gpzs",
"yfqn7i3thucgg5u4o65j6x3y":"gpersoon",
"2sfjbck4oc6hqcq233sshjmd":"gpmota",
"6owkj4v25qu46rd5a3mqdql5":["gparali","Boardgame Ramblings"],
"m56wbsmuv7jwcwb36i6aieyf":["gpawalraven","Gideon Walraven "],
"i45rcjvcatdr2shkt6w2x5by":["gplumiere","GPLumiere"],
"nr2vbthtb4nrpji4gjode3wc":"gproducer",
"ayfjzco7x7chrpobpuckiqnl":["gpemberton97","Gregory Pemberton"],
"dzmlnsll5vpj5cjiqq5gl6ak":"gps1138",
"l5y5xkccen6dazcpzh3cif4u":["gpwcbj","Gary W"],
"5ha2un2m26qdlnx36gzud5ou":"gportt",
"fdsolwodxux7fhvpj6vkiujd":"gpriv757",
"e6s2nq52uvrfpaij4apkinvx":"gpcrowden",
"xp3ieb2quelxr7dmygfyyncq":["gpeng","Graham Pengelly"],
"joq7o2qcvwhngczoskamuojz":["gportelli","Giovanni Portelli"],
"ybb47srr42kw3aly2oypcglz":"gpcdd",
"5xrqnxfohkra4sfx6irf3qyf":["gpwigglesworth","GPWigglesworth"],
"z7aamu5tud422mlrshe3b4gu":"gplord",
"puds4qg7shsbozzwku3cegys":"gpeterson",
"272h62vn7kzlfq74rif675my":"gpmurray",
"xpdbaoemmxdvu57jvj5zvqdz":"gpitarch",
"fzaz2fakppqcbxi7wk3hazgq":["gpursals","Guillem Pursals"],
"pqcmoxxotwgton3iw2uabwfh":["gped","Gabe"],
"c4cwx3fsd7yakzs6ht5austs":["gptnshl","Anshul Gupta"],
"esjfzoxc6si7mlwh7f6lwj2y":["gposers","GPOSERS"],
"2ekot2ejfnweoq33lkbvjsxk":["gpsinger","Gabe Singer"],
"spl3kf3oitdxlwrlx4pfq6qp":"gpaganini",
"bheaiap6uerce22dr7aflgle":"gpawned",
"k5pcsna7vljfa5uexpxvsyon":"gpolly",
"dpeyzcroktjfefc7ygd7oznm":"gpano",
"lj77vv2nv2oqhy5swjz64s6h":["gpap","Greg Papangeles"],
"y2dl7bpjmftusjnzuwivjqzb":"gplits",
"kdf3g5td3nmbihjpkurmsnis":["gpetrick","Gabriella M. Petrick, Ph.D. 🍇🍇🍇"],
"lom5fttiybez77k7v6o7ybbh":["gplorgtfo","Stephen"],
"ht6ikboedezr7usqvzkspacd":["gplanchat","Grégory Planchat"],
"jm5nsb6olcmyxn43ik35karw":["gpassamonti","Giovanni Passamonti"],
"glkpsgrbk2pnhjr42gu5vma4":"gpavaneli",
"tiyytkuf5etgmtdulimysd2b":["gpunktruschka","Gerald Ruschka"],
"cys5457nsxnpqoj6vsrhtcje":["gpennywoke","Greg P."],
"qx3e3xeyt64u5trqgnzgx4c6":["gpereze","Gonzalo Pérez"],
"mcnx3emwzmaddgr67356w73e":["gpop","Gpop"],
"zxyajk7dm4o6crmxdqobzwe6":["gpanel","gPanel® by Promevo"],
"eyauhxfxhklrl22vwmuj476a":["gpaolacci","Gabriele Paolacci"],
"i75hijs3jt74msdvzsbi5wma":"gpseema",
"y32vrvm6xqmjg433hj4al6x6":["gparsons","Geraldine Parsons"],
"gyqk6j4rfhvkyarqipfbn7td":["gpcd","Great Pop Culture Debate"],
"jqoibez3ywtonukqx244e2ds":["gpfansglobal","GPFans Global"],
"6vsnkz65kufa3ii7o3fp7pkx":"gpanger",
"bey7ahkmsy5vgk5hgh2qpdpa":["gpietran","Giuseppe Pietrantuono"],
"yjoqy6kwq7pglbmjv2yhzxrq":"gppi",
"ismdv654g62f35ovk3zzzraq":["gperrri","grace"],
"3z2nfaqjjqofnwl4v34n3ope":["gpgolden","Greg"],
"qbl6cvg4hr4qaui4c4ys3ca3":["gpigsrock","kazuha simp"],
"6j6k4zx5373tmlziextnu7li":["gpoutine","GPoutine"],
"oqp4mlhnfvu5piq3s3ed574g":"gpalmq",
"hhgbgg5xivtts6rh6t52n5xk":["gpmediagrp","Good People Media Group"],
"dmy36y7p2lwmdc54fjis4uez":"gpollara",
"rku2zpve22qtsvui33kfu7ag":["gpconseil","GP conseil"],
"fjxembn7zlh4zm6ns2v76bvd":["gportal","GPORTAL.COM"],
"anlnx6c5qmrkwxtljtw5y5ii":["gpseum","Teargas Diplomacy "],
"7jaxs7pwl4pi5p6k4ppbznfn":["gpilsdeb","GPILS Office of Diversity, Equity, and Belonging"],
"gd6bdgxvxccaymv6dxmhl7ob":"gpsnsfw",
"3vafruttfjw6kd2v5khikf52":["gpejournal","Global Political Economy Journal"],
"etl5tx6r5aq7s7z3vqc3fq33":"gpianta",
"vlmygx77j45znodn6xmyzuwq":["gprouty","Greg"],
"tojjxoo42ylinxquu7pnu5uy":["gpthemoron","Gp_the_moron"],
"sebk27k6o4akcvfsvo3d2d2s":["gpion","Gilles Pion"],
"7yiq4ry2nzdc4ei2lt4ol7tp":"gpanholz",
"mwpjmst2ux66oitsytklh5qf":["gpreda","Gabriela Preda "],
"4g7cdcnc4ruanmhleqg5b7dx":["gpatrickhubbard","Patrick Hubbard"],
"lpvbfohbdkq7q7vhmfzhjtr3":["gpgm","Grégory"],
"ioxah2cjzyfvvkknobrtcyt6":["gpostaire","Guillaume Postaire"],
"wmpolphnw5r2fdkmalht7rmh":["gppcarleo","Giuseppe Carleo"],
"2xkzthytkaapsiien3d2c24c":"gpaprocki",
"omgdbscg33wamn55diondanz":"gpjourno",
"nlsvpf74rpx2vgdxl2xlid5q":"gprohaska",
"nl4in4ctpr5w6u3agifcnn2j":["gporrinos","Guillermo Porriños"],
"3jvw4xromcynlo7me3be5lw3":["gpblue","GP"],
"kgludhjlc7rdxqqe33zxalqu":"gplassard",
"v7mhdjojgehguzaewaywxzdg":["gpjohanna","Johanna Hagström"],
"fctyhlccn3s7yg3bj4ndgc5f":["gpixies45","GalaxyPixies45"],
"btxhvcqiehvcsynvyipmqyff":"gpierre",
"olpx73a3hkixrnzhag2xx6h5":["gphlpp","Gabriele Philipp"],
"qhckmx3zx6b4ojspse2sroo6":"gpmvdb",
"n6hpdk6inwiuw4xnkpe665bs":["gpreeds","Grant Reeds"],
"6kcmtabcj3odvfvtnvblk6tp":"gpoiatti",
"l5e2tf6m2zxq3aozrwbfqrzo":"gpetitjaque",
"iums2r6247y3alygvl52y6jr":"gpanime",
"vrcnnlkbdy6hcsaifgjmwdmi":["gpupy","guppy"],
"puyv3vntdb6jx3v2uwjuqsce":"gppsy",
"pludryzuaasqzd5k77zpw2el":["gpprod","GP Production"],
"r5ltuq2swzrocw26loqnxo7t":"gplunk",
"in235jeximqivabdicavvtvk":["gpicot","Georg Picot"],
"rd2twcmmpd4is4whb22fpxk7":["gplayer15","GPlayer"],
"dtvwugu2wjv7yz2o7kfbcdts":["gprise","Farid, Enterprising Salvager"],
"tqkkv2jdoyfirxl7cm6ipsf2":["gpsguy","GPS"],
"ihnildduvxshfs6kqs7kaixt":"gpkaan",
"hhtb7onxjahjk4tcsx5fdw6f":["gp2304","Gabi"],
"f4zb7erkawbtnpgxeua33sj5":["gpif","GPif"],
"orjycvneeyaxn3nygg4tjgbj":["gpopesie","PoPésie"],
"34uilegmljvdsvxtxlefuso7":["gphx",".:GPHX:."],
"rzmiwlfx44zrqu4yb33qrog5":"gpil",
"opsxtjeaw7x2u5qc4m7wk4tu":"gpfriend",
"nypk2s6x42mual5ghdubbt3x":["gpmanga","GPManga!"],
"mfc3nvt2tyblq66ogajnn33j":["gpihdatabase","Global Price and Income History Group"],
"yrjco53q52wlrffusalk2uiq":"gprodi",
"xptlcfveodfl7vqwlu3hjva2":["gpp95","gpp95"],
"wh5rfon7o7hylncglnb5ar4l":"gpi",
"brpgrsrqhbqxsqyqxafpm35f":"gpinvestigativ"
}) // 2023-11-04T11:04:19.830Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
