var zv=(function(jsonp){ if (typeof zv==='function')zv(jsonp); return zv=jsonp })({
"aishaowfjhfstcmm52ew3w6d":["zvonko","Zvonko"],
"d5rkn3mbn5c5k3nsacszhtho":["zverissimo","José Verissimo"],
"fareb4ikx2hvpk6gluptn3js":["zvjedavaa","Tereza 🌍🇪🇺🇩🇪🇨🇿💚📚Sláva 🇺🇦"],
"fo5znclgqhl6oimdf7vlylm2":["zvim","zvim"],
"gnpwctys6rmyufxn5vhz5gzu":"zvychainyi",
"iblos7ce4fjmcd3cuw4cfr3t":["zven","Sven Weizenegger"],
"mjci563kfkhyniuwepdwcybb":["zvrra","twitch.tv/zvrra"],
"npburfstn2ly3xe6esqi2t4p":"zversnow",
"rfv6ajq2jlkfo2dvjdr22uvm":["zvuc.me","zvuc"],
"rudeu7fawnko2rmso3kntviu":["zvjezdanpatz","Zvjezdan Patz"],
"4q7ditasnxk5f4luyitlwgmy":"zvck",
"54hfjvqmvptnd43e3qddiaqi":["zvibe","𐂴"],
"zagdhhqpa7ggaruojrdedctn":["zveyisoglu","Zülfikar Veyisoglu"],
"fcetmssssdwxggdeibc2ruzr":"zvonn",
"quisazrimsxln563xd2vsm4i":"zve",
"k2x7phpwoo62f3uwvvxxdll4":"zvineyard",
"7bgcojvakfsdzwmyte5xcsh4":"zvalent",
"rdpxx73pqavltfrgfizudcxz":["zvu","zvuk"],
"2raqhiwg25mahnkvrmqkkavt":["zverovski","Zverovski"],
"npwucfda35tyhnsbocochbdk":"zvglobal",
"dvk277cevprlwv36lj3xi3ih":"zviadist",
"wxlxycvfm3sjvijfyh4gmrxv":"zvyyv",
"7p2hqzchdatn6rsqiappeyqc":["zvrvki","zvrvki"],
"qtvy3z3jrorbf7w3mlo5znzk":["zvarych","zvarych"],
"utzsjcrbtn266jhpb7hu3aoc":"zvr",
"fmuq5f4bakfs5ofhls5tpcyd":["zvvvvck","ZAC"]
}) // 2023-10-22T16:57:37.306Z darwinarm64 node-16.20.0 v8-9.4.146.26-node.26
